### ISSUE TITLE
第一题：以下代码输出什么，为什么？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#1]
```js
try {
    (async function() { a().b().c() })()
} catch (e) {
    console.log(`执行出错：${e.message}`)
}
```
第一反应答案是什么？为什么会这样报错？

[答案](https://github.com/KieSun/fucking-frontend/blob/main/Answer/1%20~%2010/1.md)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，[群已达扫码上线，请加好友拉你进群](https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg)。

**Comment by Turkyden** [comment]
Fucking Awesome !

**Comment by ganfubin** [comment]
a is not defined

**Comment by RoJoHub** [comment]
`ReferenceError: a is not defined`
a 都没有定义

**Comment by GuoYueXin** [comment]
ReferenceError: a is not defined

**Comment by EstherHuo** [comment]
a is not defined

**Comment by cjxiaocong** [comment]
a is not defined

**Comment by barry7** [comment]
async 约等于 Promise

**Comment by chen870370470** [comment]
执行try中语句时报错`ReferenceError: a is not defined`，因此catch也捕获不到错误。

**Comment by pengpeng9413** [comment]
ReferenceError: a is not defined

**Comment by ScarecrowG** [comment]
```ReferenceError: a is not defined```
(async function() {a().b().c() })()是个异步任务，try...catch无法捕捉，所以不会执行catch中的console
改成
```js
try {
    await (async function() { a().b().c() })()
} catch (e) {
    console.log(`执行出错：${e.message}`)
}
```
就可以catch啦```执行出错：a is not defined```

**Comment by zhouhanging** [comment]
catch也捕获不到错误，a is not defined

**Comment by tuhongwei** [comment]
执行a()时，因为a未定义，所以会报错，但因为try里面async是异步,所以不会被同步的catch捕获，即不会有console输出，最终会返回一个rejected的Promise, 所以报的错为 Uncaught (in promise) ReferenceError: a is not defined

**Comment by wanCheng7** [comment]
a is not defined

**Comment by 371311231** [comment]
ReferenceError: a is not defined

async定义的是异步任务，catch无法捕获

**Comment by jshuaishuai** [comment]
如果有异步函数的话，就不需要用try catch 了

**Comment by free-qiaochen** [comment]
ReferenceError: a is not defined；
try执行，async方法出错，相当于promise reject，错误没被catch捕获

**Comment by cn1001wang** [comment]
有一个问题，为什么new Promise里不是同步执行？当下面这段代码运行时，如果他是异步应该不会打断console.log(b)的运行
```try{
    var b=123
    var fn1=()=>{
        a()
    }
    new Promise(fn1)
    console.log(b)
}catch(e){
    console.log(e)
}
```

**Comment by tinyKingBear** [comment]
what‘s the fuck you doing here？

**Comment by pengpeng9413** [comment]
至于为啥catch 没有捕捉到，楼上很多的人都没有解释很清楚，我来回答一下我的陋见：
async + function 返回的是一个promise，promise 在自执行（FFEE）的一个作用域中是个完整的异步函数自执行了，内层函数已经执行完了，外层当然catch 不到。
想要被catch ，是在try 中发生了错误，代码中断。而一个完整promise只会在自身这一层被捕获，外面认为你这是自己的事，不能管啊。出来闹，我就管！

**Comment by zhihuifanqiechaodan** [comment]
try catch 不能捕获异步代码。 所以也不是单纯的考量promise吧。虽然他也属于异步

**Comment by XINXINP** [comment]
1.try catch捕获不到该错误 
2.按照正常语法来说 错误应该是 ReferenceError类型 a is not defined
3.可以修改一下 加一个await关键字 获取promise的返回值，使其能够被捕获到
4.也可以直接使用promise自带的catch捕获错误 （与题目无关了）

**Comment by ambit-tsai** [comment]
![image](https://user-images.githubusercontent.com/42671189/110286026-2bac8480-801f-11eb-9906-d055fe67671e.png)

**Comment by PointMountain** [comment]
1.try里面是一个自执行的async函数，async是异步的方法，try catch没办法捕获到异步方法
2.async函数返回的是promise，因为内部发生了错误，所以变成promise rejected了，错误则是a方法未定义

**Comment by blacklike** [comment]
个人见解： try catch是同步的，而async是异步的，返回的是一个Promise。而try catch只能捕获到同步函数中的异常，无法捕获到异步函数中的异常错误。而async中执行的，a().b().c()，一开始的a就会报错，因为a未定义。报错为：Uncaught ReferenceError: a is not defined
    at <anonymous>:1:1

**Comment by pengpeng9413** [comment]
我又要来提灵魂之问了？为啥try catch 不能捕获异步任务的error ，这跟浏览器的执行机制（事件循环）有关：
try catch 作为宏任务而promise是微任务，当执行promise.then(()=>callbaclk()),进入回调函数的时候，外层try catch 这个宏任务已经出栈了，跟他已经没有关系了

**Comment by cduyzh** [comment]
ReferenceError: a is not defined

**Comment by ctime-zliang** [comment]
都在说 async 是异步的，那这段代码为啥 inner 会在 outer 之前输出呢？

`
try {
    let a = 0
    ;(async function() {
        a += 1
        console.log('inner', a)
        throw new Error('123')
        // a()
    })()
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}
`

**Comment by ctime-zliang** [comment]
try {
    let a = 0
    ;(async function() {
        a += 1
        console.log('inner', a)
        throw new Error('123')
        // a()
    })()
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}

这段代码，inner 会在 outer 之前输出，为啥？

**Comment by cduyzh** [comment]
> 这段代码，inner 会在 outer 之前输出，为啥？

let a = 0;
try {
  setTimeout(foo, 1000);
  console.log("outer", a);
} catch (e) {
  console.warn("Error", e);
}

async function foo() {
  a += 1;
  console.log("inner", a);
  throw new Error("123");
  // a()
}
如果你的预期是反的可以理解下这个，

**Comment by caryye** [comment]
ReferenceError: a is not defined
try catch正常来说是可以捕获到错误的，但是由于try里面的是异步任务；try catch作为宏任务，在函数执行的时候就已经入栈，而当异步函数抛出异常时，try catch已出栈

**Comment by zhihuifanqiechaodan** [comment]
> ```js
> 尝试 {
>     让 a  =  0 
>     ; （异步 功能（） { 
>         a  + =  1
>         控制台。日志（'inner' ， a ）
>         抛出 新的 错误（'123' ）
>         // a（）
>     } ）（）
>     控制台。log （'outer' ， a ）
> }  catch （e ） {
>     控制台。警告（'Error' ， e ）
> }
> ```
> 
> 这段代码，内部会在外部之前输出，为啥？



> ```js
> try {
>     let a = 0
>     ;(async function() {
>         a += 1
>         console.log('inner', a)
>         throw new Error('123')
>         // a()
>     })()
>     console.log('outer', a)
> } catch(e) {
>     console.warn('Error', e)
> }
> ```
> 
> 这段代码，inner 会在 outer 之前输出，为啥？

promise是异步。 throw new Error('123')的时候错误被promise.reject接收，然后继续执行同步代码，等同步代码执行完执行异步爆出这个错误

**Comment by ctime-zliang** [comment]
> ```js
> try {
>     let a = 0
>     ;(async function() {
>         a += 1
>         console.log('inner', a)
>         throw new Error('123')
>         // a()
>     })()
>     console.log('outer', a)
> } catch(e) {
>     console.warn('Error', e)
> }
> ```
> 
> 这段代码，inner 会在 outer 之前输出，为啥？

本人补充一下，为啥要等 outer 输出完后，再抛错

**Comment by KieSun** [comment]
> `ReferenceError: a is not defined`
> (async function() {a().b().c() })()是个异步任务，try...catch无法捕捉，所以不会执行catch中的console
> 改成
> 
> ```js
> try {
>     await (async function() { a().b().c() })()
> } catch (e) {
>     console.log(`执行出错：${e.message}`)
> }
> ```
> 
> 就可以catch啦`执行出错：a is not defined`

老哥，你是第一位给出完整答案的，如果需要简历修改服务可以发我邮箱：zx597813039@gmail.com

**Comment by littleKnave** [comment]
ReferenceError: a is not defined
1. 立即执行(async function() {a().b().c() })()。因为返回是一个promise，所以返回一个promise.reject
2. 执行完接下来的同步任务，这时候执行完try...catch
3. 执行promise.reject，报错

**Comment by KieSun** [comment]
答案已经公布，[地址](https://github.com/KieSun/fucking-frontend/blob/main/Answer/1%20~%2010/1.md)

**Comment by ambit-tsai** [comment]
感觉上述的答案并不对。
从 async/await 的语法糖实现来看，题中的 async 函数是放在`new Promise(executorFunc)` 的`executorFunc`函数中执行的，众所周知`executorFunc`是立即执行，所以不存在什么异步任务。
而错误为什么不被 try/catch 捕获，是因为 Promise 在实例化的时候会捕获`executorFunc`的错误，所以外面是捕获不到的。

**Comment by cn1001wang** [comment]
> 感觉上述的答案并不对。
> 从 async/await 的语法糖实现来看，题中的 async 函数是放在`new Promise(executorFunc)` 的`executorFunc`函数中执行的，众所周知`executorFunc`是立即执行，所以不存在什么异步任务。
> 而错误为什么不被 try/catch 捕获，是因为 Promise 在实例化的时候会捕获`executorFunc`的错误，所以外面是捕获不到的。

我感觉你说的才是正确的，我昨天也是第一次知道Promise中的错误不会被抛到外部了。然后搜索一圈，就找到这么一篇文章翻译自V8引擎作者的文章 [从JS引擎理解Await b()与Promise.then(b)的堆栈处理](https://blog.fundebug.com/2018/07/18/javascript-engine-await-promise/) 。虽然不是和本次题目强关联，但也是在Promise与堆栈方面带给我所不知道的一面

```javascript
try {
    let a = 0
    ;(async function() {
        a += 1
        console.log('inner', a)
        throw new Error('123')
        // a()
    })()
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}
```
如上代码，他是能够输出'outer' 1 的 ;  try catch认为你这段代码没有错，所以进不了catch。Promise内部的错误应该在Promise中解决。
我想请教你有没有相关文章能够佐证这个观点。

```javascript
;(function(){
    let p
    try {
        let a = 0
        p=Promise.resolve(1).then(e=>a())
        console.log('outer', a)
    } catch(e) {
        console.warn('Error', e)
    }
    setTimeout(()=>{
        p.catch(e=>{console.warn(e)})
    },1000)
})()
```
然后我有这么一段代码，我惊奇的发现chrome控制台会在1s后把错误输出给吞回去；输出warnning。
这是什么原理

**Comment by KieSun** [comment]
> > 感觉上述的答案并不对。
> > 从 async/await 的语法糖实现来看，题中的 async 函数是放在`new Promise(executorFunc)` 的`executorFunc`函数中执行的，众所周知`executorFunc`是立即执行，所以不存在什么异步任务。
> > 而错误为什么不被 try/catch 捕获，是因为 Promise 在实例化的时候会捕获`executorFunc`的错误，所以外面是捕获不到的。
> 
> 我感觉你说的才是正确的，我昨天也是第一次知道Promise中的错误不会被抛到外部了。然后搜索一圈，就找到这么一篇文章翻译自V8引擎作者的文章 [从JS引擎理解Await b()与Promise.then(b)的堆栈处理](https://blog.fundebug.com/2018/07/18/javascript-engine-await-promise/) 。虽然不是和本次题目强关联，但也是在Promise与堆栈方面带给我所不知道的一面
> 
> 
> try {
>     let a = 0
>     ;(async function() {
>         a += 1
>         console.log('inner', a)
>         throw new Error('123')
>         // a()
>     })()
>     console.log('outer', a)
> } catch(e) {
>     console.warn('Error', e)
> }
> 如上代码，他是能够输出'outer' 1 的 ; try catch认为你这段代码没有错，所以进不了catch。Promise内部的错误应该在Promise中解决。
> 我想请教你有没有相关文章能够佐证这个观点。
> 
> 
> ;(function(){
>     let p
>     try {
>         let a = 0
>         p=Promise.resolve(1).then(e=>a())
>         console.log('outer', a)
>     } catch(e) {
>         console.warn('Error', e)
>     }
>     setTimeout(()=>{
>         p.catch(e=>{console.warn(e)})
>     },1000)
> })()
> 然后我有这么一段代码，我惊奇的发现chrome控制台会在1s后把错误输出给吞回去；输出warnning。
> 这是什么原理

这种问题其实其实查标准就好了：

![](https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/09/16152976980078.jpg)

内部 throw 被 `promise reject` 了，外部就不可能捕获到这个错误，当然不管有没有这个机制都是捕获不到的，毕竟异步代码怎么让同步代码捕获错误。

[标准具体地址](https://tc39.es/ecma262/#sec-control-abstraction-objects)

**Comment by ambit-tsai** [comment]
如上图，从 ECMA-262 的`27.7.5.1 AsyncFunctionStart`一节来看，async 函数是立即执行的，执行结果出现异常时`reject`
> 4. Set the code evaluation state of asyncContext such that when evaluation is resumed for that execution context the following steps will be performed:
> a. Let `result` be the result of `evaluating asyncFunctionBody`.
> ...
> d. If result.[[Type]] is normal, then
> &nbsp;&nbsp;&nbsp;&nbsp;i. Perform ! Call(promiseCapability.[[Resolve]], undefined, « undefined »).
> e. Else if result.[[Type]] is return, then
> &nbsp;&nbsp;&nbsp;&nbsp;i. Perform ! Call(promiseCapability.[[Resolve]], undefined, « result.[[Value]] »).
> f. Else,
> &nbsp;&nbsp;&nbsp;&nbsp;i. Assert: result.[[Type]] is `throw`.
> &nbsp;&nbsp;&nbsp;&nbsp;ii. Perform ! Call(promiseCapability.[[`Reject`]], undefined, « result.[[Value]] »).
> g. Return.

至于第二个问题，众所周知当 Promise 异常未被捕获时，会报`Uncaught (in promise) TypeError`，翻了下 ECMA-262 好像没有明确规定，延迟捕获异常要怎么办。Chrome 会吞回去，Firefox 并不会，大概是自行发挥的结果吧。
@cn1001wang

**Comment by cn1001wang** [comment]
@ambit-tsai @KieSun 感谢二位， execution context stack 我还得再研究研究 ！

**Comment by startfromscratch** [comment]
try{
    (async function(){
        await a().b().c()
    })()
}catch(e){  
    console.log(e,'报错原因-------')
}

  1 首先 try  catch  （同步）异常 报错 会执行  catch
  2 async 是一个promise 语法糖 返回一个 promise 
  3 在 async 执行栈中 a b c 3个方法
  4 在执行a的时候 会直接报错 a is nodefind  
 5  async 会返回 promise   其实在这里应该是有一个错误 但是 浏览器 读取到 a方法的错误，  到此为止  在不考虑任何因素的情况下 同步的捕获异常 肯定是捕获不到异步的方法里面的问题。

**Comment by wuqiren** [comment]
a is not defined

**Comment by DingDingSing** [comment]
```
try {
    (async function() { a().b().c() })()
} catch (e) {
    console.log(`执行出错：${e.message}`)
}
```
1. 执行出现异常  Uncaught (in promise) ReferenceError: a is not defined
2. try catch 无法捕获异常

**Comment by hua-bang** [comment]
游览器会抛出异常 a is not defined 
因为try catch无法捕获异步方法中的错误

**Comment by xiaocongWang** [comment]
个人觉得这道题考察的是 async 函数执行出错时语言层面是怎么处理的，而不是异步导致 try catch 无法捕获错误。(async function() { a().b().c() })() 并没有涉及到异步。

 @ambit-tsai 的解释比较靠谱

**Comment by rookielzy** [comment]
1. 结果为 `Uncaught (in promise) ReferenceError: a is not defined`
2. `try catch` 是同步代码，无法捕捉异步代码中的错误
3. 在 async 中，执行了未定义的 a()，因此这时候的错误被 `Promise.reject` 捕捉

**Comment by zjhlaap** [comment]
a is not defined
函数前加上async相当于把它放到了promise的executor函数内，变成了异步
因为try catch没办法捕获到异步的错误，想要得到```执行出错：a is not defined```的结果需要把捕获写到函数内部
![图片](https://user-images.githubusercontent.com/44579132/118942459-51da9300-b985-11eb-934d-f8ccf0b7226f.png)
