### ISSUE TITLE
第十二题：以下代码输出什么？为什么？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#17]
```js
;(function b() {
  b = 123
  console.log(b)
})()
```
请说明输出内容，并解释为什么

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by ByeLe** [comment]
打印的是 function b();
原因：
1.首先当全局代码块进入执行栈执行的时候，会创建其上下文，这个时候，有一个全局上下文如下
```javascript
{
  argument: {}
}
```
因为此时此刻没有初始化任何函数或者变量，所以他的上下文里面并没任何数据，
2.遇到自执行函数，自执行函数相当于一个块级作用域，当他进入执行栈执行的时候，也会创建他的上下文，他的上下文是：
```javascript
{
  argument: {}
  b: reference to function b(),
}
```
此时此刻的上下文总共有两个，一个全局上下文，一个自执行函数的上下文
```javascript
{ //  全局上下文
  argument: {}
}

{ // 自执行函数上下文
  argument: {}
  b: reference to function b(),
}
```
3.执行自执行函数，b = 123;这是一个赋值操作，b = 123 与 window.b = 123 是一样的结果（js的赋值运算，你不知道的JS中有讲）给全局上下文初始化一块内存用来存储b,并且赋值为123。
此时的上下文变成：
```javascript
{ //  全局上下文
  argument: {}
  b: 123
}

{ // 自执行函数上下文
  argument: {}
  b: reference to function b(),
}
```
4.函数最后执行console.log(b);我们知道js中存在一作用域链的，当他在自己上下文中找不到这个变量的时候，才会去他的上级去找，那么很显然，我这个自执行函数的上下文中有这个变量b，因此呢，他打印的是function b()
 
最后买个广告，上下文的讲解连接：https://juejin.cn/post/6937934980609736740

**Comment by Zhao-Null** [comment]
b = 123 是给全局变量b赋值为123，打印时候会先在当前作用域寻找b，发现是函数，打印。

**Comment by fantasticfbaby** [comment]
IIFE中的foo函数名相当于是使用const关键字定义的，因此没有办法对一个常量再赋值. 
在strict mode下，直接TypeErroe类型的错误，这类错误同数据类型相关. 
在non-strict mode下，会忽略对常量的赋值. 
[知乎链接](https://www.zhihu.com/question/60063924)

**Comment by huang-ping** [comment]
```javascript
// 不同意b是全局变量，debugger一下就知道了，如果b = 123是全局，打印的时候也是打印全局
        // 这个函数是通过函数表达式定义的，函数名称将会（且只会）作为函数体（作用域内）的本地变量
        // b就是函数name，函数的name属性是只读的，无法修改
        var fun = function funName(){}
        console.log(fun.name)  // 输出 funName
        fun.name = '呵呵'
        console.log(fun.name)  // 输出 funName
```

**Comment by goldEli** [comment]
> 3.执行自执行函数，b = 123;这是一个赋值操作，b = 123 与 window.b = 123 是一样的结果（js的赋值运算，你不知道的JS中有讲）给全局上下文初始化一块内存用来存储b,并且赋值为123。

@ByeLe window 上没有b，所以b并不是全局变量
![image](https://user-images.githubusercontent.com/18217162/112083458-0d6b8a80-8bc2-11eb-9ad8-920da895ea2e.png)

**Comment by docterlei** [comment]
> IIFE中的foo函数名相当于是使用const关键字定义的，因此没有办法对一个常量再赋值.
> 在strict mode下，直接TypeErroe类型的错误，这类错误同数据类型相关.
> 在non-strict mode下，会忽略对常量的赋值.
> [知乎链接](https://www.zhihu.com/question/60063924)

赞同老哥的回答 运行完此代码在浏览器下面打印 b 出现的是undefined 且在浏览器下面运行此代码 会报 (Uncaught TypeError: Assignment to constant variable.)
```
<script>
    "use strict";
     ;(function b() {
        b = 123
        console.log(b)
    })()
</script>
```

**Comment by liuy1994** [comment]
我猜，
立即执行函数如果有名字，的确是用const 定义的，自然不允许在函数内部再次赋值。
如果是匿名函数的话，是可以将b 定义到全局变量中去的。
![image](https://user-images.githubusercontent.com/26955033/112083956-f6796800-8bc2-11eb-9832-c661af66dae2.png)

**Comment by docterlei** [comment]
> IIFE中的foo函数名相当于是使用const关键字定义的，因此没有办法对一个常量再赋值.
> 在strict mode下，直接TypeErroe类型的错误，这类错误同数据类型相关.
> 在non-strict mode下，会忽略对常量的赋值.
> [知乎链接](https://www.zhihu.com/question/60063924)

赞同老哥的回答 运行完此代码在浏览器下面打印 b 出现的是undefined 且在浏览器下面运行此代码 会报 (Uncaught TypeError: Assignment to constant variable.)
```
<script>
    "use strict";
     ;(function b() {
        b = 123
        console.log(b)
    })()
</script>
```

**Comment by goldEli** [comment]
### 在严格模式下测试此段代码
![image](https://user-images.githubusercontent.com/18217162/112084057-1f016200-8bc3-11eb-83c2-45033c16e48c.png)

执行到 b = 123 时报错了，报错信息为不能为常量赋值。说明了立即执行函数是个常量，不能进行赋值。
由此猜测在非严格模式赋值也会失败但不会报错报错，所以最终打印结果为 `function b`

**Comment by QuXiaoMing** [comment]
![image](https://user-images.githubusercontent.com/11560552/112084992-ac918180-8bc4-11eb-9291-e81a99f14c8c.png)
打印function b; b = 123 并未赋值给 window.b

**Comment by l0ng09** [comment]
```js
;(function b() {
  b = 123
  console.log(b)
})()

// 输出 function：b

function b() {
  b = 123
  console.log(b)
}
b()
b()

// 输出 123
// b is not a function 

// 本质上这两段代码应该是等同的，但是输出结果却不一样
// 这个是因为自执行函数会创建一个封闭的作用域，其中函数名称应该是一个静态量无法被赋值
```

**Comment by makejun168** [comment]
### 答案
返回的是 function b

### 原因分析
1. 首先外面是包裹了一个自执行函，看过jQuery源码都了解到 自执行函数相当于一个块级作用域，形成作用域就会有作用域链
2. 然后第二个点是关于函数的变量提升，通过 function b 的方法定义函数，不仅会提前声明而且会变量提升，而 定义 **b = 123** 这种方法 等于 **window.b = 123** 是在上级作用域定义了 变量b
3. 最后在 **console.log(b)** 时候 会先在作用域链上查找，固打印出 **function b**

**Comment by vandvassily** [comment]
> IIFE中的foo函数名相当于是使用const关键字定义的，因此没有办法对一个常量再赋值.
> 在strict mode下，直接TypeErroe类型的错误，这类错误同数据类型相关.
> 在non-strict mode下，会忽略对常量的赋值.
> [知乎链接](https://www.zhihu.com/question/60063924)

佩服大佬们

```js
var b = 1;
;(function b() {
  b = 123
  console.log(b)
})()

console.log(b)

// function b
// 1

;(function c() {
  b = 123
  console.log(b)
})()

console.log(b)

// 123
// 123
```

**Comment by Talljack** [comment]
返回的是function b
因为立即函数执行时会形成函数作用域，函数作用域内的b赋值操作会将b挂载到window上即全局作用域，而打印的b在函数作用域内部存在函数，所以会先打印函数内部的b

**Comment by monadaa** [comment]
function b()

(function() { 
 // 使用 IIFE 可以模拟块级作用域，即在一个函数表达式内部声明变量，然后立即调用这个函数。这样位于函数体作用域的变量就像是在块级作用域中一样。ECMAScript 5 尚未支持块级作用域，使用 IIFE模拟块级作用域是相当普遍的。
})();

**Comment by XINXINP** [comment]
答案: 输出 function b 和undefined
因为（function b(){})()是立即执行函数，通过测试可知，
- 正常情况下，立即执行函数自己创建一个独立的作用域，全局作用域访问不到
- 因为本题中不是匿名函数，有函数名称b，所以该函数名可以在函数内部能被识别，且只能在函数内部被识别
- 同时，该函数被认为是常量赋值，后续修改都是失效的
- 如果我们在函数内部用严格模式测试，就会报错TypeError: Assignment to constant variable

**Comment by AbigaiL533** [comment]
function b,
因为在IIFE中，里面的函数相当于直接const的一个b，所以直接对其赋值是无效的，然后会打印出来fn b;
如果使用use static的情况，会运行到 b=3时 报TypeError：Assignment to constant variable

**Comment by yang-1234** [comment]
```js
输出：function b() {
              b = 123
              console.log(b)
          }
```

**Comment by dorothyDing** [comment]
function b
1. IIFE中的函数是函数表达式，而不是函数声明
2. 函数表达式里函数名只在该函数内部有效，并且此绑定是常量绑定

**Comment by Turkyden** [comment]
marked

```js
;(function b() {
  b = 123
  console.log(b)
})()
```

**Comment by Leexuetao** [comment]
function b() {
  b = 123
  console.log(b)
}

原因是：立即执行函数IIFE中的函数是函数表达式，只在函数内部有效，并且绑定的是常量绑定，也就是b是个常量，不可修改，（在严格模式下报错）所以输出的是b函数

1、函数表达式与函数声明不同，函数名只在该函数内部有效，并且此绑定是常量绑定
2、对于一个常量进行赋值，在strict模式下会报错，非strict模式下静默失败
3、IIFE中的函数是函数表达式，而不是函数声明

(function b() {
'use strict'
  b = 123
  console.log(b)
})() 
相当于
const b = function() {
  b = 123
  console.log(b)
}
b()
![image](https://user-images.githubusercontent.com/28001619/112120446-32c7bb00-8bf9-11eb-92cc-a42c79e4f3eb.png)

**Comment by muzishuiji** [comment]
IIFE中的函数名b相当于是使用const关键字定义的，因此没有办法对一个常量b再赋值.
在strict mode下，直接TypeErroe类型的错误，这类错误同数据类型相关.
在non-strict mode下，会忽略对常量的赋值.
```javscript
var b = 1;
;(function b() {
  b = 123
  console.log(b)
})()

console.log(b)

// function b
// 1

;(function c() {
  b = 123
  console.log(b)
})()

console.log(b)

// 123
// 123
```
非严格模式下:
![image](https://user-images.githubusercontent.com/18276045/112133548-c5228b80-8c06-11eb-9274-6087a1dac832.png)

严格模式下:
![image](https://user-images.githubusercontent.com/18276045/112133421-a7edbd00-8c06-11eb-883b-30e8be247513.png)

**Comment by mengzhe510** [comment]
;(function b() {
  b = 123
  console.log(b)
})()
// 输出function b()
// b函数在IIFE中为函数表达式，并且该函数为具名函数，绑定为常量绑定，函数名在内部有效
// 在IIFE中，给常量赋值，在严格模式下，会报TypeError，在非严格模式下，忽略对常量赋值

**Comment by xt1995726** [comment]
输出函数b
立即执行函数会生成一块内部块级作用域，由于该立即执行函数不是匿名函数，拥有name，函数b只能在当前块级作用域访问，相当于const声明，内部b变量无法修改常量声明的值，所以输出函数b

**Comment by adam-zhou** [comment]
当遇到具名的函数表达式的时候，会创建一个辅助的特定对象，只存储函数表达式的名称，然后添加到函数作用域的最前端，该值只读，并且不可以被删除，所以不能对该值进行操作。

所以当运行到b=123时，js引擎需要读取b，并且赋值，而此时b存储的是常量，所以没法赋值，打印function b

**Comment by 1742284240** [comment]
输出函数b
自执行函数（IIFE）是函数表达式（FE），具名函数表达式（函数表达式有名称）执行时会创建一个只存储函数名称的特殊对象，这个特殊对象即不在父变量对象（VO）中，也不在函数表达式的活动对象（AO）中，然后添加在函数的作用域中

**Comment by SunshineZJJ** [comment]
b=function b; 因为自执行具名函数是函数表达式并且函数名等同于const定义的常量不可修改，所以b=123赋值不生效；不报错的原因是严格模式下会抛出常量不可修改的异常，非严格模式静默错误

**Comment by sunsmeil** [comment]
```js
;(function b() {
  b = 123
  console.log(b)
})()
// 1. 运行到b函数时 代码编译阶段，b的函数作用域会放在作用域栈中，会对里面的变量扫描。变量b 因为没有声明，非严格模式时被挂到window上
// 2. 代码执行阶段，执行到 b = 123,会对window.b进行赋值。执行到console时 会先查函数作用域里面有没有，然后向上会到全局的词法环境找到了函数b 返回。（window.b在变量对象里 优先级小于词法环境。let const也在这词法环境里面）
```

**Comment by sunsmeil** [comment]
```js
;(function b() {
  b = 123
  console.log(b)
})()
// 输出 函数b
```
1. 执行到立即执行函数时，由于它本质是个匿名函数压入到调用栈中。
2. 压入后会对函数内部进行扫描，执行上下文创建，
  - 变量提升会先对 变量b进行提升，然后是函数b提升 会覆盖掉变量b.(及函数优先级大于变量)
  - 还有this值指向window
3. 把函数b压入调用栈，执行 b = 123,但此时b在作用域链中是 函数b, 且这个函数b是在词法环境中，不能被重新赋值 (相当于const还是有点不理解，此处放在词法环境还需要论证)
4. 打印b 即为函数b

**Comment by hua-bang** [comment]
立即执行函数的函数名相当于常量定义 即const定义。若进行赋值 所以非严格模式下 会无效果 严格模式下会报错

**Comment by linger0239** [comment]
1. IIFE中的函数是函数表达式，函数名只在该函数内部有效，并且此绑定是常量绑定。
2. 对于一个常量进行赋值，在 strict 模式下会报错，非 strict 模式下静默失败。

**Comment by Little-cute** [comment]
答案是：函数b
原因是：非严格模式下，首先立即执行函数会在内部形成块级作用域
1. 由于该立即执行函数不是匿名函数，拥有name，函数b只能在当前块级作用域访问，相当于const声明，内部b变量无法修改常量声明的值
2. 假如函数没有name则输出的是123
