### ISSUE TITLE
第十四题：JS 类型

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#19]
请问 JS 基本类型和对象类型中各有哪些类型？

对于这些类型我们如何判断具体的类型。比如数组是对象类型，可以通过 `Array.isArray` 等方法判断是数组。

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by goldEli** [comment]
```js
// 基本类型：number string boolean undefined null symbol
// 引用类型：Object Function Array

var a = 123;
console.log(typeof a === "number"); // true
a = "123";
console.log(typeof a === "string"); // true
a = true;
console.log(typeof a === "boolean"); // true
a = undefined;
console.log(typeof a === "undefined"); // true
a = null;
console.log(a === null); // true
a = Symbol();
console.log(typeof a === "symbol"); // true

a = {};
console.log(typeof a === "object"); // true
function func() {}
console.log(typeof func === "function"); // true
a = [];
console.log(a instanceof Array); // true
```

**Comment by liuy1994** [comment]
1. 基本数据类型

   Null, Undefined, Number, String, Boolean, Symbol

   直接使用`typeof a` 获得类型

2. 引用数据类型

   Object, Array, Function, Date, RegExp, Error 等，其实都是Object

   对于Function，`typeof  a === 'function'`

   对于其它`typeof a === 'object'`

   直接使用`a.constructor.name` 获取构造函数的名称

   基本数据类型同样可以使用`a.constructor.name` 的方式

**Comment by huang-ping** [comment]
```javascript
isNaN Array.isArray instanceof constructor 等
// 比较全面的
let toString = Object.prototype.toString
ƒ toString() { [native code] }
toString.call(null)
"[object Null]"
toString.call(undefined)
"[object Undefined]"
toString.call(true)
"[object Boolean]"
toString.call(1)
"[object Number]"
toString.call(null)
"[object Null]"
toString.call(undefined)
"[object Undefined]"
toString.call('aa')
"[object String]"
toString.call([])
"[object Array]"
toString.call(Date)
"[object Function]"
toString.call(new Date)
"[object Date]"
toString.call({})
"[object Object]"
toString.call(/\d/)
"[object RegExp]"
toString.call([])
"[object Array]"
```

**Comment by makejun168** [comment]
### Javascript 六种数据类型
5种的是原始类型，1种对象类型
1. Object
2. Number
3. String
4. Boolean
5. Null
6. Undefined

### Object 对象包含6种引用类型的对象
1. Function
2. Arguments
3. Math
4. Date
5. RegExp
6. Error

#### JavaScript 数据类型检测
* typeof 返回的是字符串类型 适合基本类型 和 function的检测
* instanceof obj instanceof Object 左操作数是一个对象 右操作数是一个函数对象或者函数构造器 左边如果不是对象就会直接返回 false
* Object.prototyoe.toString
* constructor 不稳定的方法 会被改写

| 方法名称 | 语法 | 返回值 | 特殊情况 | 
| --- | --- | --- | --- |
| typeof | typeof params 判断基础类型  | 字符串 "number" "boolean" "function" "undefined" | typeof null "object" typeof NaN "number" typeof(undefined) "undefined" typeof Function.prototype "function" 遇到null的判断的时候会失效 |
| instanceof | 判断对象类型，通过原型链判断 obj instanceof Object | 返回布尔值   | 不同window或者iframe间的对象类型检测不能使用instanceof |
| Object.prototyoe.toString.apply(Object) | Object.prototyoe.toString.apply(Object) | 字符串 "[object Array]" "[object Function]" "[object Null]" "[object Undefined]" | IE6/7/8 Object.prototype.toStirng.apply(null) 返回的是 "[object Object]" |

**Comment by benbtx** [comment]
number string boolean  null undefine symbol  
object
6+1,
object.prototype.tostring.call()

**Comment by cduyzh** [comment]
```
最新的 ECMAScript 标准定义了 9 种数据类型:

6 种原始类型，使用 typeof 运算符检查:
undefined：typeof instance === "undefined"
Boolean：typeof instance === "boolean"
Number：typeof instance === "number"
String：typeof instance === "string
BigInt：typeof instance === "bigint"
Symbol ：typeof instance === "symbol"
null：typeof instance === "object"。
Object：typeof instance === "object"。任何 constructed 对象实例的特殊非数据结构类型，也用做数据结构：new Object，new Array，new Map，new Set，new WeakMap，new WeakSet，new Date，和几乎所有通过 new keyword 创建的东西。
Function：非数据结构，尽管 typeof 操作的结果是：typeof instance === "function"。这个结果是为 Function 的一个特殊缩写，尽管每个 Function 构造器都由 Object 构造器派生。
记住 typeof 操作符的唯一目的就是检查数据类型，如果我们希望检查任何从 Object 派生出来的结构类型，使用 typeof 是不起作用的，因为总是会得到 "object"。检查 Object 种类的合适方式是使用 instanceof 关键字。但即使这样也存在误差。
```

**Comment by l0ng09** [comment]
![image](https://user-images.githubusercontent.com/16459847/112413150-a6cda480-8d5a-11eb-8217-dd2fb77894b4.png)
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Data_structures

**Comment by AbigaiL533** [comment]
Seven Data Types that are primitives, checked by typeof operator:
undefined : typeof instance === "undefined"
Boolean : typeof instance === "boolean"
Number : typeof instance === "number"
String : typeof instance === "string"
BigInt : typeof instance === "bigint"
Symbol : typeof instance === "symbol"
Structural Types:
Object : typeof instance === "object". Special non-data but Structural type for any constructed object instance also used as data structures: new Object, new Array, new Map, new Set, new WeakMap, new WeakSet, new Date and almost everything made with new keyword;
Function : a non-data structure, though it also answers for typeof operator: typeof instance === "function". This is merely a special shorthand for Functions, though every Function constructor is derived from Object constructor.
Structural Root Primitive:
null : typeof instance === "object". Special primitive type having additional usage for its value: if object is not inherited, then null is shown;

我是看了以后再copy的，所以我没问题

**Comment by mynamexiaohui** [comment]
基本类型 

​	undefined,null,string,boolean,number,symbol,bigint（前几天学到的）

引用类型

 	object

内置对象

​	内置对象是object的子类型，有String,Number,Boolean,Object,Function,Array,Date,RegExp,Error

如何判断类型

1. typeof 对于基本类型除了null之外都可以判断，null会返回object，**原理是因为，不同的对象在底层都是为二进制的，在JavaScript中二进制的前三位为0的话就会被判断为object类型，null的二进制表示全是0，所以执行typeof会返回object**，对于引用类型会返回object和function两种情况。

2. 通过interface来判断一个对象是否是某个构造函数的实例

3. object.prototype.tostring.call()通过返回的字符串来判断类型

4. 通过constructor来判断对象是否属于当前类型 如array.constructor === Array

**Comment by yang-1234** [comment]
// 基本类型有：Number,BigInt,string,boolean,null,undefined,Symbol
// 对象类型有：Array,Object,function,Date
let a;
let arr = []
let obj = {};
let str = 'test';
let sym = Symbol();
let bigNum = BigInt("9999999999999999")
let reg = new RegExp()
// Number,string,boolean,undefined,Symbol 都可以使用typeof判断
// 其中null虽然是基本数据类型，但是不能用typeof判断，null值表示一个空对象指针，使用typeof检测null值会返回object，这也是js遗留下来的bug
console.log(typeof a) //undefined
console.log(typeof bigNum)//bigint
console.log(typeof sym)//symbol
// instanceof可以判断Array,Object,Date,RegExp,但是还不能很清晰的判断出一个实例是数组还是对象或方法。
console.log(arr instanceof Array); // true
console.log(arr instanceof Object); // true，Array 是Object的子类
function testFun() { }
console.log(testFun instanceof Function); // true
console.log(testFun instanceof Object);//true
console.log(reg instanceof RegExp); // true
// Object.prototype.toString.call()基本上所有对象的类型都可以判断
console.log(Object.prototype.toString.call(null))//[object Null]
console.log(Object.prototype.toString.call(bigNum))//[object BigInt]
console.log(Object.prototype.toString.call(sym))//[object Symbol]
console.log(Object.prototype.toString.call(arr))//[object Array]
console.log(Object.prototype.toString.call(new Date())); // [object Date]
console.log(Object.prototype.toString.call(testFun)); // [object Function]
console.log(Object.prototype.toString.call(reg)); // [object RegExp]
// 对象类型实例还可以通过constructor来判断，可以通过constrcutor对象来访问它的构造函数
console.log(bigNum.constructor === BigInt);// true
console.log(arr.constructor === Array);// true
console.log(obj.constructor === Object);// true
console.log(str.constructor === String)// true
console.log(sym.constructor === Symbol)// true
console.log(testFun.constructor === Function);// true

**Comment by Turkyden** [comment]
marked

**Comment by sunsmeil** [comment]
- **基础数据类型**： string number boolean null undefined symbol bigInt  （null被拆出去了 ？ 喵喵喵）
- **引用类型**： object
- **类型判断**：
   - 基础类型：typeof除了 null 都可以正确判断。
   - 引用类型可以用： instanceof 原型链进行判断，constructor 进行判断（不安全的因为可能被改变）。
   - 都可以用Object.prototype.toString.call进行判断返回[object ***]类似的字符串
   -  数组类型： 除了以上 还可以用isArray
   - null:  可以用 === null 判断。（此处涉及 ==  和 === 隐式转换）

**Comment by Fox-54500** [comment]
1、typeof 可以大致的判断基础类型 number、bigint、string、boolean、undefined、symbol，null 
2、虽然属于基本类型，但是typeof null === 'object'，所以一般如果判断null的话尽量直接 value === null 吧
3、对象类型 Object 、Array、Function、Map、Set、Weakmap、WeakSet 等
4、判断实例来源什么原型的话 就用instance 比如：dog instanceof Dog === true、Function instanceof Object === true

上面都是大佬的发言，感觉自己心里能想到的就比较浅薄了~

**Comment by yanxiaolazy** [comment]
基本类型包括:
Boolean
Null
Undefined
String
Number
Symbol
BigInt (ES2020规范定义)
对象类型包括: Object

判断数据类型：
1、typeof
但是会有问题
typeof null时，会返回'object' 
typeof console.log 会返回'function'
对于未声明的变量也会返回'undefined'

2、使用 Object.prototype.toString.call可以判断所有的类型
function dataType(type) {
  return Object.prototype.toString.call(type)
}

**Comment by qll19930105** [comment]
基本类型：null, undefined, boolean, string, number, symbol, bigInt;
引用类型： object

判断方法：Object.prototype.toString().call()

**Comment by monadaa** [comment]
基本类型：null， undefined，boolean，string，number，symbol
引用类型：object

如何判断类型
1. typeof 对于基本类型
> typeof可以识别出基本类型boolean,number,undefined,string,symbol，但是不能识别null。不能识别引用数据类型，会把null、array、object统一归为object类型,但是可以识别出function。
> 所以typeof可以用来识别一些基本类型。
2. 通过interface来判断一个对象是否是某个构造函数的实例
> 从结果中看出instanceof不能识别出基本的数据类型 number、boolean、string、undefined、unll、symbol。
但是可以检测出引用类型，如array、object、function，同时对于是使用new声明的类型，它还可以检测出多层继承关系。
3. object.prototype.tostring.call()通过返回的字符串来判断类型
4. 通过constructor来判断对象是否属于当前类型 如array.constructor === Array

**Comment by dorothyDing** [comment]
共有8种数据类型（7种基础类型+1种对象类型）

基础类型
1. String
2. Boolean
3. Number
4. null
5. undefined
6. Symbol
7. BigInt

引用类型
1. Object

判断方法：
1. typeof  
typeof判断基础类型结果如图：
![image](https://user-images.githubusercontent.com/17584537/112417817-4bec7b00-8d63-11eb-9d0c-f34da66981d4.png)
⚠️：null 被判断为 object
typeof判断 引用类型的时候返回 object

2. instanceof 用于检测构造函数的 prototype 属性是否出现在某个实例对象的原型链上。 

3. Object.prototype.toString.call() 所有类型都可以判断，并且细分到子类型

**Comment by huahua5525** [comment]
请问 JS 基本类型和对象类型中各有哪些类型？

对于这些类型我们如何判断具体的类型。比如数组是对象类型，可以通过 Array.isArray 等方法判断是数组。
基本类型
null undefined boolean number string symbol BigInt
对象类型
object
typeof可以判断基本类型，除了null，null 被判断为 object

**Comment by XINXINP** [comment]
### js数据类型（共9种）分为原始值和引用值
#### 原始类型（7）（原始值）
- 使用typeof就可以判断
- string
- number
- boolean
- undefined
- BigInt
- symbol
- null（不能用typeof）
#### Object(1)（引用值）（对象被认为是特定引用类型的实例）
- 使用instance of通过原型判断，可使用Object.prototype.toString.call()
##### 原始值包装类型
- Number 
- String 
- Boolean 
- ##### 基本引用类型
- Date 
- RegExp 
##### 单例包装类型
- Global
- Math
##### 集合引用类型
- Array 
- Set 
- Map
- weakSet
- weakMap
#### Function(1)

**Comment by free-qiaochen** [comment]
7 种原始类型，使用 typeof 运算符检查:
undefined：typeof instance === "undefined"
Boolean：typeof instance === "boolean"
Number：typeof instance === "number"
String：typeof instance === "string
BigInt：typeof instance === "bigint"
Symbol ：typeof instance === "symbol"
null：typeof instance === "object"。

Object：typeof instance === "object"。任何 constructed 对象实例的特殊非数据结构类型，也用做数据结构：new Object，new Array，new Map，new Set，new WeakMap，new WeakSet，new Date，和几乎所有通过 new keyword 创建的东西。
Function：非数据结构，尽管 typeof 操作的结果是：typeof instance === "function"。这个结果是为 Function 的一个特殊缩写，尽管每个 Function 构造器都由 Object 构造器派生。
记住 typeof 操作符的唯一目的就是检查数据类型，如果我们希望检查任何从 Object 派生出来的结构类型，使用 typeof 是不起作用的，因为总是会得到 "object"。检查 Object 种类的合适方式是使用 instanceof 关键字。但即使这样也存在误差。

**Comment by Lisheri** [comment]
function checkType(target, type) {
       return Object.prototype.toString.call(target).toLocaleLowerCase().replace(/\[|\]|(object )/g, '') === type
}

**Comment by Lisheri** [comment]
function checkType(target, type) {
return Object.prototype.toString.call(target).toLocaleLowerCase().replace(/[|]|(object )/g, '') === type
}

**Comment by Lisheri** [comment]
原始类型: stirng number boolean symbol bigInt null undefined
引用类型: object function map set weakMap date regExp Array等

判断方式(万能):
function checkType(target, type) {
return Object.prototype.toString.call(target).toLocaleLowerCase().replace(/[|]|(object )/g, '') === type
}

**Comment by SunshineZJJ** [comment]
7种基本类型：number,string,undefined,boolean,symbol,bigint, null
引用类型 object（date,function,array...）
console.log(typeof 11); // number
			console.log(typeof '11' ); // string
			console.log(typeof true ); // boolean
			console.log(typeof undefined ); // undefined
			console.log(typeof Symbol()); // symbol
			a = BigInt(1111111);
			console.log(typeof a); //  bigint
	              console.log(typeof null ); //object--null值表示一个空对象指针，而这也正是typeof检测null值时会返回object的因。
			console.log(typeof {} ); // object

**Comment by panalanjun** [comment]
### JS基本类型:
String
Boolean
Number
undefined
null
Symbol
BigInt

#### 结论：
基本类型除了null都可以通过typeof即可判断区分，分别为
"string"
"boolean"
"number"
"undefined"
"symbol"
"bigint"

对于null，最好使用「value === null」来进行判断，因为「typeof null === 'object'」，会与实际上的object类型混淆，
由此在实际工作上，很常见的语句：
if (typeof obj === 'object' && obj !== null) { }


### 常用的对象类型（引用类型）
Object
Function
Array
Date
RegExp
Error

#### 下面通过例子加以区分
```javascript
var a = {};
console.log(typeof a);					// object
console.log(a instanceof Object);		// true

var b = function() {};
console.log(typeof b);					// function
console.log(b instanceof Function);		// true

var c = [];
console.log(typeof c);					// object
console.log(c instanceof Array);		// true
```

#### 下面通过实例化对象方式验证结果
```javascript
var c = new Array();
console.log(typeof c);					// object		
console.log(c instanceof Array);		// true

var d = new Date();
console.log(typeof d);					// object
console.log(d instanceof Date);			// true

var f = new RegExp();
console.log(typeof f);					// object
console.log(f instanceof RegExp);		// true
```


#### 下面举一个非实例化例子
```javascript
a = Object;
console.log(typeof Object);				// function

d = Date;
console.log(typeof d);					// function
console.log(d instanceof Date);			// false
console.log(new d instanceof Date);		// true
```

#### 结论：
引用类型使用typeof输出，会发现实际上都是一个"function";
实例化后，除了Function外，都是"object"类型，Function为"function"类型;
对于实例化对象类型，一般可以使用instanceof来加以判断区分，
由此在实际工作上，很常见的语句需要区分开 {} 和 []：
if (obj instanceof Object && !(obj instanceof Array)) { console.log("是对象，非数组"); }

附上instanceof解析：
instanceof 运算符用于检测构造函数的 prototype 属性是否出现在某个实例对象的原型链上。

**Comment by chengfengfengwang** [comment]
1.原始数据类型
  string, number, boolean, symbol, bigInt, null, undefined
2.对象类型
  Date, Array, Function, RegExp, Maps等...
基本数据类型可以用typeof 判断，唯一例外是typeof null 返回'object'
对象类型用 instanceof 判断

**Comment by muzishuiji** [comment]
1. 基本数据类型:
Null, Undefined,Boolean,String,Number,Symbol
对于基本数据类型的类型判断通常使用 `typeOf`,也可以使用`Object.prototype.toString.call()`;
对于Null这个数据类型使用`typeof null`的结果是Object,所以可以直接使用`value === null`,来判断这个数据类型.
2. 引用数据类型
Object,Array,Function

对于引用数据类型的判断可以使用 `instance of`,也可以使用`Object.prototype.toString.call()`;
这时候你肯定会很好奇`Object.prototype.toString.call()`的原理,他为什么可以来判断引用类型的数据类型.

**`Object.prototype.toString.call()`的原理**

我也还在找,有兄弟能够说的清楚的话,忘不吝赐教,回复我这个评论就好啦~

接下来的几种数据类型使用 `instanceof`来判断. `instanceof`的原理简单来说就是判断数据类型A是否在变量B的原型链上:

```JavaScript
let a = {};
// 判断 Object是否在a的原型链上
a instanceof Object; // true
```
3. 原始值包装类型
  Number
  String
  Boolean

4. 单例包装类型
  Global
  Math

5. 集合引用类型
  Array
  Set
  Map
  weakSet
  weakMap

**Comment by fantasticfbaby** [comment]
原始类型
1. boolean
2. number
3. string
4. undefined
5. null 通过typeof获得的类型是null
6. symbol
7. bigInt

引用类型
1. Object 以下通过typeof获得的类型都是object
   1. Date
   2. RegExp
   3. Array
   4. Set
   5. WeakSet
   6. Map
   7. WeakMap
   8. ...
2. Function 通过typeof获得的类型都是function

用Proxy搭配Object.prototype.toString.call写了一个简易的通用类型判断工具
```
let TypeChecker = new Proxy(
  {},
  {
    get(target, key, receiver) {
      let matchRes;
      if ((matchRes = key.match(/is(.*)/))) {
        let type = matchRes[1];
        if (target[key]) return target[key];
        const judgeFunc = function(t) {
          return Object.prototype.toString.call(t).slice(8, -1).toLowerCase() === type.toLowerCase();
        };
        target[key] = judgeFunc;
        return judgeFunc;
      } else {
        return function() {
          throw new Error("invalid function")
        };
      }
    },
  }
);

console.log(TypeChecker.isArray([])); // true
console.log(TypeChecker.isRegExp(/aa/)); // true
console.log(TypeChecker.isNumber('1')); // false

```

**Comment by 1742284240** [comment]
**JS 基本类型**
Number
String
Undefined
Null
Boolean
Symbol
Bigint

**对象类型**
Object
Function

var a;
> 判断Number、String、Undefined、Boolean、Symbol、Bigint都可以用typeof直接判断

> 判断Null类型：


    1、 直接用全等号（===）判断；
    2、Object.prototype.toString.call(a) === '[object Null]'

> 判断数组Array
    1、Array.isArray(a) === true;
    2、a instanceof Array === true
    2、Object.prototype.toString.call(a) === '[object Array]';

> 判断Function
    Object.prototype.toString.call(a) === '[object Function]'

**Comment by BillScott1024** [comment]
基本数据类型 ： string， number， boolean, symbol，null ,undefined
判断方法： string， number， boolean, symbol, undefined  用 typeof 判断
null 用 === null 判断
Object 对象用 instanceof  判断

**Comment by 371311231** [comment]
1. 请问 JS 基本类型和对象类型中各有哪些类型？
- **最新ECMAScript标准中共定义了9种数据类型**
- **（原始）基本数据类型：Boolean、Null、Undefined、Number、String、Symbol、BigInt**
- **引用类型：Object、Function**

2. 对于这些类型我们如何判断具体的类型。比如数组是对象类型，可以通过 Array.isArray 等方法判断是数组？
- **Boolean: typeof instance === 'boolean'**
- **Null: typeof instance === 'object'**
- **Undefined: typeof instance === 'undefind'**
- **Number: typeof instance === 'number'**
- **String: typeof instance === 'string'**
- **Symbol: typeof instance === 'symbol'**
- **BigInt: typeof instance === 'bigint'**
- **Object: typeof instance === 'object'**
- **Function: typeof instance === 'function'**
- 精确判断类型
```javaScript
function getType(target) {
return Object.prototype.toString.call(target).replace(/\[|\]|(object )/g, '')
}

getType(null)  // Null
getType(undefined)  // Undefind
getType(true)  // Boolean
getType(1)  // Number
getType('aa')  // String
getType(BigInt(1221212121212121212121212))  // BigInt

getType(Symbol('a'))  // Symbol
getType([])  // Array
getType(new Date())  // Date
getType({})  // Object
getType(/\w/)  // RegExp
```

**Comment by docterlei** [comment]
基本类型: stirng number boolean symbol bigInt null undefined
引用类型: object function map set weakMap date regExp Array

判断方式: Object.prototype.toString.call(param)

**Comment by ByeLe** [comment]
基本数据类型：
null, undefined boolean  string number 存在于栈上
引用数据类型：
Object,Array, Date, Function, RegExp
判断方法：
typeOf: 只能判断出 undefined boolean  string number，而且null用typeod的话也是属于Object
instanceOf  检测构造函数的prototype是否在所要检测的数据的原型链上，能完全鉴别
Object.prototype.toString.call(被检测的数据)

**Comment by mengzhe510** [comment]
基本类型： string,number,boolean,null,undefined,symbol,biginit
引用类型： object
    细分 object,function,array,date,regexp,map,set等
判断类型：
 基本类型 可以用typeof判断（null比较特殊，被识别为object，用xxx===null判断）
 引用类型用instanceof判断
 或是用Object.prototype.toString.call()判断

**Comment by xt1995726** [comment]
### 基础类型
- undefined
- null
- string
- number
- boolean
- Symbol
- BigInt
### 引用类型
- Object
- Function
- Array
- Math
- Date
- RegExp
- Map
- WeakMap
- Set
- WeakSet

### 判断类型的方法
- typeof 判断基础类型，但是`null`为`object`
- instanceof 判断引用类型，但是行为可被修改
- toString 判断所有，没有任何问题

**Comment by vandvassily** [comment]
```js
let toString = Object.prototype.toString;
let a;

// 1. undefined
console.log(typeof a === 'undefined')
console.log(toString.call(a) === '[object Undefined]')

// 2. number
a = 1;
console.log(typeof a === 'number')
console.log(toString.call(a) === '[object Number]')

// 3. string
a = '';
console.log(typeof a === 'string')
console.log(toString.call(a) === '[object String]')

// 4. boolean
a = true;
console.log(typeof a === 'boolean')
console.log(toString.call(a) === '[object Boolean]')

// 5. null
a = null;
// typeof null === ‘object’，这是考点
console.log(a === null)
console.log(toString.call(a) === '[object Null]')

// 6. symbol
a = Symbol('test')
console.log(typeof a === 'symbol')
console.log(toString.call(a) === '[object Symbol]')

// 7. Array
a = [];
console.log(Array.isArray(a))
console.log(a instanceof Array)
console.log(toString.call(a) === '[object Array]')

// 8. Function
a = function(){};
console.log(typeof a === 'function')
console.log(toString.call(a) === '[object Function]')

// 8. Function
a = {};
console.log(typeof a === 'object' && !Array.isArray(a) && a !== null)
console.log(toString.call(a) === '[object Object]')

// 9. bigINT
a = BigInt(14);
console.log(typeof a === 'bigint')
console.log(toString.call(a) === '[object BigInt]')
```

**Comment by chen870370470** [comment]
### 基础类型

- undefined
- null
- string
- number
- boolean
- Symbol
- BigInt

### 引用类型

- Object
- Function
- Array
- Math
- Date
- RegExp
- Map
- WeakMap
- Set
- WeakSet
```js
 // 检测方式
;(function () {
  var class2type = {}
  var toString = class2type.toString //=>Object.prototype.toString
  // 设定数据类型的映射表
  ;[
    'Boolean',
    'Number',
    'String',
    'Function',
    'Array',
    'Date',
    'RegExp',
    'Object',
    'Error',
    'Symbol',
  ].forEach((name) => {
    class2type[`[object ${name}]`] = name.toLowerCase()
  })
  function toType(obj) {
    if (obj == null) {
      // 传递的值是null或者undefined，就返回对应的字符串
      return obj + ''
    }
    // 基本数据类型都采用typeof检测
    return typeof obj === 'object' || typeof obj === 'function'
      ? class2type[toString.call(obj)] || 'object'
      : typeof obj
  }
  window.toType = toType
})()

**Comment by Leexuetao** [comment]
请问 JS 基本类型和对象类型中各有哪些类型？

对于这些类型我们如何判断具体的类型。比如数组是对象类型，可以通过 Array.isArray 等方法判断是数组。


基本类型： String, Number, Boolean, Undefined, Null， Symbol

对象类型：Object, Function, Array, RegExp, Date

判断数据类型
1、typeof 可以判断基本类型除null 和对象类型的function
例如： 1) var a = 'ab'; typeof a // 'string'
      2) var a = 123;  typeof a // 'number'
      3) var a = true;  typeof a // 'boolean'
      2) var a = undefined;  typeof a // 'undefined'
      2) var a = Symbol();  typeof a // 'symbol'
      2) var a = function() {};  typeof a // 'function'
2、Array.isArray(arr) 可以判断数组类型
例如： 1）var arr = [1,2]; Array.isArray(arr) // true
3、Object.prototype.toString.call(value) 可以判断所有类型,返回一个[object Xxx]
例如： 
![image](https://user-images.githubusercontent.com/28001619/112498255-4e7dbd80-8dc1-11eb-8502-0322738491c4.png)

**Comment by LXJ2** [comment]
### JS的数据类型
- 原始数据类型
   - number
   - string
   - null
   - undefined
   - boolean
   - symbol
   - bigint
- 对象数据类型（引用类型）
   - object
            + {}  
            + []  array
            + /^$/ RegExp
            + new Date
            + ...
   - function 函数类型「可执行对象」
#### 检查数据类型的方法
- 1、 typeof检测 基本数据类型，返回数据类型，null除外，为"object",JavaScript值表示为32位的字符。最低的3位作为一种标识，表示值是对象、整数、浮点数或者布尔值。对象的标示是000。而为了表现null值，引擎使用了机器语言NULL指针，该字符的所有位都是0。而用typeof就是检测值的标志位，这就是为什么它会被认为是一个对象的原因。
- 2、用instanceof检测复杂数据类型object和function，返回
- 3、Array.isArray(arr) 可以判断数组类型，返回boolean类型

**Comment by Easay** [comment]
JS的基本数据类型有：undefined、boolean、number、string、null
JS的引用数据类型有：Array、Function、Object、RegExp、Date
基本类型的值放在栈内存中，引用类型的值放在堆内存中。引用类型的变量放在栈内存中，用来引用堆内存中的值。
判断数据类型的方式有：
1.typeof
typeof 变量名 ,返回一个字符串，主要有以下结果：
值未定义->'undefined';
对象或null ->'object';
布尔值 ->'boolean'
数字 ->'number'
字符串 ->'string'
2.instanceof
a instanceof Array, 返回布尔值
在a的原型链上查找，找到Array，则返回true，直到null都没找到，则返回false
3.constructor
a.constructor， 返回a的构造函数，进而判断类型，不能对null和undefined使用，因为它们不是对象构造的。
4.Object.prototype.toString.call();
null ->[object null]

**Comment by LGY-color** [comment]
function getType(obj){
  let type = typeof obj;
  if(type !== 'object'){
    return type;
  }
  return Object.prototype.toString.call(obj).replace(/^\[object (\S+)\]$/,'$1');
}

getType([]); //Array
getType({}); //Object
getType(function(){}); //function

**Comment by Chrisyjs** [comment]
基本类型：string、number、null、undefined、boolean、symbol、bigint
引用类型：Array、Object、RegExp、Date、Function

- 利用 typeof 判断
  - typeof 可以判断除 null 以外的基础类型，引用类型除了 Function，其他都返回 'object'
- 利用 instanceof 判断引用类型
  - 类似于 [] instanceof Array
- 利用 toString 判断引用类型
  - 类似于 Object.prototype.toString.call({}) === '[object Object]'

**Comment by dogloving** [comment]
判断类型：
![image](https://user-images.githubusercontent.com/17293065/117421610-45037b80-af51-11eb-9a11-450888731510.png)
判断数组：
![image](https://user-images.githubusercontent.com/17293065/117421644-4df44d00-af51-11eb-8666-a8ffca0cc023.png)
