### ISSUE TITLE
第二题：以下代码输出什么，为什么？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#2]
```js
try {
    let a = 0
    ;(async function() {
        a += 1
        console.log('inner', a)
        throw new Error('123')
        // a()
    })()
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}
```

这道题目是昨天题目的演化版，更有趣了，当然本质是一样的，我们就当巩固了。

问题是输出顺序是什么，为什么会这样？

再加个问题，`async` 是返回一个 `Promise` 对象，为啥函数体内的抛错能被返回的 `Promise` 捕获到。

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，[群已达扫码上线，请加好友拉你进群](https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg)。

[答案](https://github.com/KieSun/fucking-frontend/blob/main/Answer/1%20~%2010/2.md)

**Comment by ming556** [comment]
inner 1
outer 1
Uncaught (in promise) Error: 123
先调用异步方法，a+=1，输出1，同时输出outer 1，随后异步方法抛出异常123

**Comment by Turkyden** [comment]
Fucking Awesome !

```diff
- VM404:2 Uncaught (in promise) ReferenceError: a is not defined
```

- a 函数未定义，`a is not defined`
- try catch 无法捕获异步错误
- async 是 promise 的语法糖，会报发生在 `in Promise` 错误

**Comment by cduyzh** [comment]
### 昨天有幸看到过评论里有讨论这道题的 最大的争议就是抛出123的异常那里
### 输出结果：
```
inner 1
outer 1
(node:1128) UnhandledPromiseRejectionWarning: Error: 123
```

## # 原因：
async定义了一个会返回promise的函数，此时自执行的抛出了异常被reject了，可以看做异步函数的回调，进入了队列中，因为是微任务，
这是任务队列里还有console.log('out' ,a)未执行，执行完后再去执行微任务里的回调即throw new Error('123')

**Comment by yanxiaolazy** [comment]
inner 1
outer 1
Uncaught (in promise) Error: 123

- 被async修饰的function具有异步特征，但总体上会按着同步代码的方式求值，因此a += 1会影响后面的a的值。
- 由throw抛出的错误是异步的无法在同步的catch中被捕获到，所以不会执行catch块

**Comment by Turkyden** [comment]
> * 被async修饰的function具有异步特征，但总体上会按着同步代码的方式求值，因此a += 1会影响后面的a的值。

```js
let a = 0
    ;(async function() {
       window.setTimeout(() => {
         a += 1
        console.log('inner', a)
       }, 1000)
    })()
    console.log('outer', a)
```
这样的话 outer a 应该是 0

**Comment by yukailis** [comment]
inner 1
outer 1
Uncaught (in promise) Error: 123

宏任务进入宏任务队列，微任务进入微任务队列。
代码当做宏任务执行，先执行自执行函数，打印inner，1；
async修饰的函数同步代码执行异步操作，throw new Error会当做异步代码执行，进入微任务队列；
然后继续执行当前宏任务，因为async代码同步执行问题，打印outer，2；
当前宏任务执行完毕，try cathch 只能捕获同步代码的抛错，走不到 catch 里面，最后执行throw new Error('123')

**Comment by tuhongwei** [comment]
> Fucking Awesome !
> 
> ```diff
> inner 1
> outer 1
> - VM489:6 Uncaught (in promise) Error: 123
> ```
> 
> * async 是 Promise 的语法糖，属于**微任务**，优先执行异步任务，输出 `inner 1`
> * 随即在该异步任务内 throw new Error('123')
> * 此时 `console.log('outer', a)` 取到的 a 是 1
> * 最后捕获异常异步代码主动抛出的异常
> 
> > 很奇怪，为什么 `console.log('outer', a)` 取到的 a 是 1 ？？？

async并不是Promise的语法糖，它是Generator 函数的语法糖

**Comment by wanCheng7** [comment]
输出结果：
- inner 1
- outer 1
- Uncaught (in promise) Error: 123

个人理解：
- 由于async后面的函数会返回一个promise，所以catch不到异步报错，catch里的东西不会打印
- try里面的代码，首先执行的是宏任务console.log('inner', a)
- 然后是宏任务console.log('outer', a)
- 最后才是微任务promise的reject，throw new Error('123')

**Comment by crush996** [comment]
inner 1
outer 1
Uncaught (in promise) Error: 123
在 async 中，报错信息会显示 in promise。try cathch 只能捕获同步代码的抛错，走不到 catch 里面。

**Comment by HuskyToMa** [comment]
## 结果

- inner 1
- outer 1
- Uncaught (in promise) Error: 123

## 为什么

首先执行自执行函数中的console， 然后会执行到thorw方法， 但是这个方式是一个被async function， 所以他的抛错会被延迟到微任务的结束，也就是后面的console会优先执行，执行完成之后才会去执行thorw抛出的错误，并且因为是一个微任务的原因，所以try...catch无法捕获

**Comment by HuskyToMa** [comment]
## 结果

- inner 1
- outer 1
- Uncaught (in promise) Error: 123

## 为什么

首先执行自执行函数中的console， 然后会执行到thorw方法， 但是这个方式是一个被async function， 所以他的抛错会被延迟到微任务的结束，也就是后面的console会优先执行，执行完成之后才会去执行thorw抛出的错误，并且因为是一个微任务的原因，所以try...catch无法捕获

**Comment by HuskyToMa** [comment]
## 结果

- inner 1
- outer 1
- Uncaught (in promise) Error: 123

## 为什么

首先执行自执行函数中的console， 然后会执行到thorw方法， 但是这个方式是一个被async function， 所以他的抛错会被延迟到微任务的结束，也就是后面的console会优先执行，执行完成之后才会去执行thorw抛出的错误，并且因为是一个微任务的原因，所以try...catch无法捕获

**Comment by XINXINP** [comment]
inner 1
outer 1
Uncaught (in promise) Error: 123
1.js代码的执行顺序
2.try catch 只捕获到同步代码，捕获不到promise in里的错误
3.;(function(){})()这里走的是同步，且a的作用域就是外面a的作用域

**Comment by ScarecrowG** [comment]
chrome执行结果如下：
![image](https://user-images.githubusercontent.com/40666766/110436338-130b9f80-80ef-11eb-9e94-1c388b463dba.png)
**知识点：** async 作为Generator的语法糖，async自带执行器，它返回一个Promise对象，可以用then调用用catch捕获
- Promise内部为同步代码，先执行 ```a += 1```此时```a === 1```，输出```inner 1```
- ```throw new Error('123')```会被```reject```接收，丢进微任务队列里（不会打断当前宏任务的执行）
- 执行```console.log('outer', a)```输出```outer 1```
- 同步任务执行结束，没有error被catch
- 执行微任务，微任务队列里有被reject接收的```throw new Error('123')```，报错```Uncaught (in promise) Error: 123```
当然我们也可以这样改
```js
try {
    let a = 0
    ;await (async function() {
        a += 1
        console.log('inner', a)
        throw new Error('123')
        // a()
    })()
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}
```
执行结果如下：
![image](https://user-images.githubusercontent.com/40666766/110437787-b3ae8f00-80f0-11eb-8784-9aba2798da06.png)

**Comment by Timo534** [comment]
##执行结果

**Comment by Timo534** [comment]
## 执行结果
inner 1
outer 1
Uncaught Error: 123
## 理由
可以把题目中的代码转化成下面代码
```
try {
    let a = 0
    new Promise((resolve, reject) => {
      a += 1
      console.log('inner', a)
      reject('123')
    })
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}
```
由于try{}catch(){}只能捕获同步代码的异常，因此无法捕获异步代码Promise中抛出的错误，所以最后会抛出Uncaught Error

**Comment by Ecaknight** [comment]
inner 1
outer 1
Error 123

**Comment by muzishuiji** [comment]
inner 1
outer 1
VM61:6 Uncaught (in promise) Error: 123
    at <anonymous>:6:15
    at <anonymous>:8:7

async 返回的是一个Promise对象,其内部跑抛出的错误,无法被try...catch捕获. 而async定义的function的内部代码是同步的,所以会顺序执行先打印 inner 1,然后执行console语句打印 outer 1.接着遇到throw语句抛出错误.

**Comment by kevin9281** [comment]
输出结果：
```
inner 1
outer 1
Uncaught (in promise) Error: 123
```

回答：

1. 先执行宏任务，执行完毕后，立即执行当前微任务队列中的所有微任务
2. async 定义的方法 方法内没有await 都是同步执行 内部形成闭包
3. console.log('inner', 1) 然后返回一个promise对象 抛出一个异常 123
4. 执行 console.log('outer', 1)
5. promise 内部抛出的错误 throw error 不会被外面的try catch捕获到

**Comment by pengpeng9413** [comment]
> 我感觉最多👍 的没有点出大家疑惑的核心问题，宏任务和微任务就不说了，上一题已经解释的很清楚了，catch 这里肯定不会进去！
> 这里主要解释的问题是：throw new Error('123')
> 这个错误的抛出为啥在浏览器中执行中，会是最后一个？
> 明明和console.log("inner", a);在同一个执行上下文啊 ？
> 这里 @ ScarecrowG 答案是我觉得很好的答案：
> **重点（敲黑板）**
> 
> 1. async + function是返回promise，当执行到throw new Error('123')时，抛出错误，函数执行中断，错误被隐式Promise.reject()接收，进入回调，这里被推入到一个新的事件循环的 微任务队列，注意这里的是**新的一轮事件循环**开始了。
> 2. 执行前一轮事件循环的宏任务：console.log('outer', a)
> 3. 执行完前一轮的宏任务，勤劳的浏览器又要关注stack 里的任务了，于是浏览器抛出
>    Uncaught (in promise) Error: 123
> 4. 理解该题async funtion 里面的是同步代码，回调才是“异步”，所以 console.log('inner', a) 最先打印。
> 5. async 是 Generator的语法糖，部署了symbol.interator , 但是无论如何都逃离不了js 是单线程，必须要靠回调解决异步任务的本
>    质。
> 6. 很多人学习宏任务和微任务，并没有关注宿主环境，没有思考为啥会有宏任务和微任务之分，都是任务按顺行执行不好么？
>    这就涉及到我们的宿主环境和js 引擎如何合作的问题了，抛开宿主环境，干扯什么宏任务微任务怎么也扯不干净，这时候
>    我们要需要一个更大的宏观视角，向上溯源，为什么会有这套机制（浏览器是如何工作的，好了，扯远了）：
>    在S3版本以及之前的版本，js 本身是没有异步执行的能力的，只能顺序执行，简单粗暴挺好么，这时候的合作方式是：
>    浏览器把一段代码交给JS引擎，引擎按顺序执行，此时任务是浏览器发起的，老前端🐶们还记得ajax么，那么ajax 又是个啥玩
>    意儿呢，核心在于XMLHttpRequest对象，而XMLHttpRequest是浏览器提供的对象哦。所以以前异步任务的执行是这样的“刀
>    耕火种”，感兴趣的可以了解js,和浏览器的发展历史（本人有个大胆的想法，写一本web前端的前世今生）
>    es5后有了Promise 之后，JS 引擎自身可以发起任务了，这里聊到我们的重点：
>    **我们把宿主发起的任务称为宏观任务，把 JavaScript 引擎发起的任务称为微观任务**。
>    简而言之：就是反复“等待 - 执行”，周而复始。
>    我们继续回答之前的疑惑，为啥有宏任务和微任务之分，答案在于：js引擎也可以发起异步任务了为了浏览器可以正常工作
>    （谁叫JS是单线程语言呢）。
>    ![image](https://user-images.githubusercontent.com/17780650/110582799-b324ff80-81a7-11eb-8218-bf077a5a1697.png)
>    看着有点像洋葱模型对不对，但是其实和洋葱模型是有差别的，这里很多文章说微任务总是比宏任务先执行，这种调调不知道
>    祸害了多少前端er, 正确的论述应该是：一个宏任务是包含许多微任务队列的，微任务总会在下一个宏任务之前执行。

**Comment by yancongwen** [comment]
```js
try {
    let a = 0
    ;(async function() {
        a += 1
        console.log('inner', a)
        throw new Error('123')
    })()
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}
```

和下面的代码是等价的：

```js
try {
    let a = 0
    ;(function() {
        return new Promise((resolve, reject) => {
            a += 1
            console.log('inner', a)
            reject(new Error('123'))
        })
    })()
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}

```

又可以简化为：

```js
try {
    let a = 0
    new Promise((resolve, reject) => {
        a += 1
        console.log('inner', a)
        reject(new Error('123'))
    })
    console.log('outer', a)
} catch(e) {
    console.warn('Error', e)
}

```

## 答案

```js
inner 1
outer 1
Uncaught (in promise) Error: 123
```

## 涉及到的知识点

- async函数一定会返回一个promise对象，如果一个async函数的返回值看起来不是promise，那么它将会被隐式地包装在一个promise中；
- try catch 无法捕获异步任务中的异常，不管是微任务还是宏任务；
- promise 中的异常（reject）只能使用 Promise.prototype.catch 捕获；
- promise 中的代码是同步任务，then 和 catch 中的代码才是异步；
- JavaScript 中的事件循环机制：
    - 首先执行宏任务；
    - 执行过程中，遇到的微任务和宏任务将被挂起，放入任务队列；
    - 宏任务执行完成之后，执行被挂起的微任务；
    - 检查任务队列中的宏任务，执行；
    - 循环上述流程；

**Comment by wuqiren** [comment]
基础有点差，我居然认为立即执行函数形成一个独立的作用域，然后就没办法访问外部变量，自认为输出一个 a is not defined。
立即执行函数的作用是创建一个独立的作用域，这个作用域的变量，外部无法访问

**Comment by noshower** [comment]
这道题目，前端基础不好的人，看别人的回答容易被人误导，分辨不出谁对谁错。

最好的方式是看规范。

还有就是 尝试手写 Promise ，手写 async await 的实现。 

其次也可以看 babel 编译后的代码。 

这道题目的关键是：Promise 内部的报错去哪了？

**Comment by Turing-ld** [comment]
答案：
```js
inner 1
outer 1
(node:18196) UnhandledPromiseRejectionWarning: Error: 123
```
跑去复习一波js的执行机制，直接自信。
async看着有点难受，改一改：
```js
try {
  let a = 0;
  function func() {
    return new Promise((resolve, reject) => {
      a += 1;
      console.log('inner', a);
      throw new Error('123')
    });
  }
  func(); // （1）
  console.log('outer', a);
} catch (e) {
  console.log('出错了：', e);
}
```
> 疑惑：Promise构造器的回调还是同步的，那么抛出的错误应该会中止整个代码的呀
```js
// 我把上述代码（1）处改成
func().catch(err => {
  console.log(err) // 123
})
```
懂了，throw被隐式reject出去了。所以这个抛出错误的代码被当作微任务，整段js执行(第一次宏任务)后才开始执行微任务。
至于为啥不会被try catch捕获，因为她只能捕获同步任务的，微任务属于异步。

**Comment by rookielzy** [comment]
从上一个问题中学习到 `try catch` 无法捕捉异步代码错误，因此这里的输出为：
1. inner 1
2. outer 1
3. 抛出错误 123（并不是 `try catch` 捕捉的）
