### ISSUE TITLE
第十六题：以下代码输出什么？为什么？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#21]
```js
let length = 10
function fn() {
  console.log(this.length);
}
let obj = {
  length: 5,
  method(fn) {
    // 两次调用各输出什么
    fn()
    arguments[0](0)
  }
}
obj.method(fn, 1)
```

请说明输出内容，并解释为什么

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by Turkyden** [comment]
markded

**Comment by Zhao-Null** [comment]
0  2 ,第一个let,this指向window，打印当前 frame和 iframe数量  第二个this指向arguments

**Comment by XINXINP** [comment]
- 答案
0
2
- 原因
- 已知上述代码会执行两次fn函数，只不过两次执行的this指向是不一样的，第一次指向全局作用域，因为length使用let赋值，所以改变不了this.length,（因为我正在浏览器的打印台测试）所以会输出当前窗口中frames的数量0，node环境中会输出undefined
- 第二次this指向arguments,arguments.length 指的是传递实参的个数，obj.method(fn, 1)传递两个实参，所以为2

**Comment by louwenqiang** [comment]
打开 学到了

**Comment by monadaa** [comment]
0
2
1. 第一个打印的this.length会指向window，而window中的length属性表示你当前页面有几个iframe；
2. function fn(){console.log(this.length)} 中的this等于arguments，它有两个实参，因此arguments的length值为2。

**Comment by yancongwen** [comment]
## 答案

0、2

## 相关知识点

- let 声明的变量并不会进行变量提升，也不会全局污染；
- window.this 返回当前窗口中包含的框架数量(框架包括frame和iframe两种元素)；
- 函数中的 this 指向问题：
      - 全局调用，指向window
      - 对象调用，指向该对象
      - 构造函数，指向新对象
      - 函数嵌套，不会继承外层函数的 this
      - 箭头函数没有自己的执行上下文，指向外层this

## 解析

- 第一次调用，相当于是函数嵌套而已，this 仍然指向原来的 this，即全局window；let  声明的 lenght 并没有覆盖window 中的length；window.length 返回当前窗口中包含的框架数量；
- 第二次调用，相当于是 arguments 参数对象调用的fn，因此this 指向arguments，因此 this.lenght === arguments.length;

**Comment by fantasticfbaby** [comment]
```
let length = 10
function fn() {
  console.log(this.length);
}
let obj = {
  length: 5,
  method(fn) {
    // 两次调用各输出什么
    fn() // 0，调用的主体对象是全局对象，因此打印的是globalThis.length 在浏览器环境下返回当前页面iframe数量 0，在node环境下返回undefined
    arguments[0](0) // 2，等同于arguments.fn(0)，调用的主体对象是arguments，因此打印的是arguments.length，其值为2
  }
}
obj.method(fn, 1)

```

**Comment by Chrisyjs** [comment]
输出：
0
2
- 第一次调用，this 指向 window，window.length 表示页面中 iframe 的数量。并且 let 声明的变量不会绑定到 window 上。所以输出 0
- 第二次调用，相当于 arguments.fn(0)，this 指向 arguments，arguments.length，所以输出2

**Comment by free-qiaochen** [comment]
0/undefined,2;
第一次fn调用。this指向global，window.length:在浏览器环境下返回当前页面iframe数量 0，在node环境下返回undefined;
第二次调用， arguments[0](0) =》 arguments.fn(0),this指向arguments，arguments.length是两个参数，为2

**Comment by dorothyDing** [comment]
0 2
原因：
1. 函数的直接调用 在非严格模式下指向window对象，window.length会返回当前窗口中包含的框架数量(框架包括frame和iframe两种元素). 所以为0

**Comment by Leexuetao** [comment]
输出：0 2

fn() // 第一次，调用fn,this指向window,window的length默认为0，let length = 10并不是修改的window.length
          arguments[0](0) // 第二次，arguments的第0个是fn,调用fn，fn中的this指向的arguments，arguments中的length为2（一个fn,一个1）

**Comment by makejun168** [comment]
### 科普小知识

这里考察的this 指向的问题，这里我想提一提 window.length 这个属性，相信很多人都不知道这是干嘛的

***
### window.length

查找页面上的frames数量，并改变每一frame元素的src属性为"www.runoob.com"：


代码内容摘录自菜鸟教程

```js
<html>
<body>
 
<iframe src="http://www.microsoft.com"></iframe>
<iframe src="http://www.google.com"></iframe>
<iframe src="http://www.youtube.com"></iframe>
 
<script>
for (var i=0; i<frames.length; i++) {
    frames[i].location="http://www.baidu.com"
}
</script>
 
</body>
</html>

```

**Comment by vandvassily** [comment]
```js
let length = 10
function fn() {
  console.log(this.length);
}
let obj = {
  length: 5,
  method(fn) {
    // 两次调用各输出什么
    fn()
    arguments[0](0)
  }
}
obj.method(fn, 1)
// window.length的值
// arguments.length

// 1. let const 声明，变量并不会挂载到 window 上；var 声明，变量会挂载到 window上
// 2. fn()，fn作为普通函数调用时，内部 this 指向 window
// 3. arguments 是类数组，{0: fn, 1: 1, length: 2}；arguments[0](0)，相当于 arguments.fn(0)，函数内 this 指向 arguments
```

**Comment by AbigaiL533** [comment]
第一个在浏览器中输出0，在node中输出undefined，
第二个输出2

第一个this指的是window，在window中，length指的是当前页面frame和iframe的数量，为0；
在node环境中，直接返回undefined
第二个输出的是argument[0](0),输出的是arguments的长度，调用的时候{ 0: fn , 1: 1 }，arguments的长度也就是2了

**Comment by muzishuiji** [comment]
```JavaScript
0;   // 第一次fn的执行没有显式或者隐式的绑定this,所以此时的fn相当于在全局调用,this指向全局对象(非严格模式下是window,严格模式下是undefined), `var`声明的变量如果在方法中，则为局部变量；如果在全局中，则相当于定义了一个全局对象的属性并赋值.而`let`, `const`只是在当前代码块中声明一个变量,故这段代码非严格模式下,会打印`window.length`的结果,为0.

2; // 通过arguments来引用fn,相当于将fn的this隐式绑定了arguments,所以this.length打印的是arguments.length.
```
显示绑定

bind, call, apply, new

隐式绑定

通常是作为某个对象的方法的绑定,例`obj.methodName` 或者 `arr[index]`.

**Comment by yanxiaolazy** [comment]
学习了

**Comment by learnRy** [comment]
```javascript
  let length = 10
  function fn() {
    console.log(this.length);
  }
  let obj = {
    length: 5,
    method(fn) {
      // 两次调用各输出什么
      fn()
      arguments[0](0)
    }
  }
  obj.method(fn, 1)
  // 在node 环境下运行，undefined, 2
  // this的指向是有运行的时候决定的， 有四种方式，1.new构造, 2.强制绑定（apply, call, bind）, 3.作为对象方法的调用, 4.其他情况指向全局（window
  // 所以第一次调用指向全局，正常情况打印10，由于js引擎机制，let定义的变量不会绑定在全局对象（node）所以打印undefined, 在(window)打印包含的框架数量(框架包括frame和iframe两种元素).
  // 第二次调用符合this指向的四种方式的第三种（作为对象方法的调用）arguments的length 为 2
```

**Comment by yiyu66** [comment]
0/undefined
2
第一个this指向window，浏览器中this.length是frame和iframe的数量，let声明变量时，不存在声明提升，length属性实际上并没有添加到window对象中。如果改成var length = 10，第一个输出为10.
第二个，MDN：使用 arguments.length来确定传递给函数参数的个数，然后使用arguments对象来处理每个参数。两个参数所以是2
学习了学习了

**Comment by huang-ping** [comment]
> 第一次打印结果未知，fn的this指向window，打印的是window.length，即iframe数
> 第二次打印的是2，fn的this指向argument，打印的就是argument的长度

**Comment by 1742284240** [comment]
0和2

js作用域是静态的（词法作用域），在函数定义时就确定了函数作用域；

 fn()直接调用时，this是window，let声明的变量不在window下，window.length找到的是页面iframe的数量：0

arguments[0](0)跟arguments[0]()是一样的，arguments[0]()里面的this是arguments，arguments是obj.method的，obj.method传了2个参数，arguments.length=2。

**Comment by chen870370470** [comment]
输出：
0
2

原因：
1.第一次调用fn是window调用的，因此this.length就是window.length，是当前窗口中的框架数量（框架包括frame和iframe两种元素）。
2.第二次调用指向的是arguments，因此this.length就是arguments.length，是2。

**Comment by mengzhe510** [comment]
输出0和2
原因：
1、第一次的fn指向window，let length为块级作用域并不会给window赋值，此时this.length为当前窗口框架的数量（即frame和iframe）
2、第二次指向arguments，this.length为arguments的数量

**Comment by l0ng09** [comment]
```js
let length = 10

function fn() {
  console.log(this.length);
}

let obj = {
  length: 5,
  method(fn) {
    // 两次调用各输出什么
    fn()
    arguments[0](0)
  }
}

fn()

obj.method(fn, 1)

// window 中输出 0  2
// node 中输出 undefined 2

// 第一个 fn 的调用是函数调用，所以直接指向 window ，所以输出 this.length  === window.length === 0 
// window.length 指的是当前窗口中框架的数量（iframe,frame）可以参考 mdn ，这个不查一下还真不知道
// 第二个是 2 ，因为调用者是 arguments， arguments.length === 2,所以输出2
```

**Comment by 371311231** [comment]
第二个打印2，this隐式绑定到arguments上输出参数长度。第一个不知。 学习了 感谢大佬们。

**Comment by hua-bang** [comment]
0
2

第一个fn是由window对象调用，所以this指向window，默认为0
第二个相当于arguments对象调用了fn，所以此时的this指向的是arguments，此时他也有两个参数，所以为2
