### ISSUE TITLE
第十七题：以下代码输出什么？为什么？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#22]
```js
var a = 0
var b = async () => {
  a = a + await 10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？
```

请说明输出内容，并解释为什么

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by huang-ping** [comment]
> 结果：
```javascript
// 1 1
// 2 10
```
### 我猜是这样的
> 执行b函数时候，表达式从左到右计算的，先取a的值，此时a为0，类似于 ```a + await 10 => 0 + await 10```，
> 遇到await，一个异步任务不用多说了
> 执行a++, a为1
> 打印 1 1
> 执行异步代码  ```a = 0 + 10```，  此时```a``` = 10
> 打印 2 10

**Comment by Zhao-Null** [comment]
1 1 ， 2 10
理由： 同步运行a++，b是一个async，没到await是同步执行，此时a作为活动变量已经存储进b的上下文，await异步，主线程结束，输出 2 10。

**Comment by vandvassily** [comment]
```js
var a = 0
var b = async () => {
    a = a + await 10
    console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？

// 1 1
// 2 10

// 1. b()，async返回的是promise对象，遇到 await前的代码是同步执行的
// 2. js代码均为从左到右进行执行，在加法运算时，会先确定左值，再确定右值；即 a = 0 + (await 10);
// 3. a++， a = 0 + 1，a为1
// 4. console.log('1', a)， 打印 1 1
// 5. a = 0 + 10，a为10，打印 2 10

// 如果换个顺序，打印结果就不一样了

var a = 0
var b = async () => {
    a = await 10 + a
    console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？

// 1 1
// 2 11
```
参考 **孤月蓝风** 的回答
[js赋值语句执行，在有函数的情况下执行顺序究竟是怎样的？](https://segmentfault.com/q/1010000015430069)

**Comment by muzishuiji** [comment]
```JavaScript

var a = 0
var b = async () => {
  a = a + await 10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？
执行结果: 

// 1 1 
// 2 10

代码做以下修改:
var a = 0
var b = async () => {
  a = a +  10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？

执行结果:

// 2 10
// 1 11

```

**Comment by yancongwen** [comment]
## 答案
1 1
2 11

## 原题可以改造为
```js
var a = 0
var b = () => {
    let 值引用 = a
    Promise.resolve().then(() => {
        a = 值引用 + 10
        console.log('2', a)
    })
}
b()
a++
console.log('1', a)
```

**Comment by louwenqiang** [comment]
答案：
1 1
2 10

遇到 await的时候会挂起，此时 a=0+await 10,执行后面的同步任务，
先会执行a++=>1, 打印console.log('1',a),再执行回之前挂起的  a=0 +10=>10

**Comment by yiyu66** [comment]
# 1 1
# 2 10
b()执行后遇到await进行异步执行，此时a=0被保存下来。向下运行输出1 1。然后回过头执行a = a + await 10 等于a=0+10,输出2 10；计算从左到右执行学到了

**Comment by free-qiaochen** [comment]
1,1
2,10；
![image](https://user-images.githubusercontent.com/24800988/112922527-33070f80-913f-11eb-9bfe-64ce9ab57905.png)

**Comment by SunshineZJJ** [comment]
声明a,b后按顺序执行，函数b先执行，走到await的时候开始等待，该异步操作=>a=0+await10;先执行外部同步执行的代码a++,所以外部打印a=1;同步代码执行完毕进入之前等待的异步方法执行流程，a=0+10=10

**Comment by XINXINP** [comment]
- 答案
1,1
2,10
考察js运行机制-事件循环，由上面代码可知，异步代码为 await 10; 
根据代码自上向下执行，简单过程如下
- 先执行b()函数，此时a为0，所以a = a+await 10;可以看作a = 0 +await 10;await 10;为异步函数会进入任务队列，会等待当前代码段所有同步代码执行完后执行。同时在b函数内部 await 10以下的代码也会等待await 10执行完后执行；
- 接着在全局作用域执行 a++;(a=1)
- 接着打印a的值(1,1)
- 同步代码全部执行完后，执行b函数内部的 await 10; (a = 0 + 10 = 10)
- 接着打印 (2,10)
## 新增测试
var a = 0
setTimeout(function () {
    console.log("455");
},0)
var b = async function() {
    console.log(a,"ooop");
  a = a + await 10
  console.log('2', a) // -> ？
  setTimeout(function () {
    console.log("655");
},0)
}
b()
setTimeout(function () {
    console.log("755");
},0)
setTimeout(function () {
    console.log("1");
    b()
},0)
a++
console.log('1', a)
#### 验证：
- 宏任务和微任务
- 每执行一个宏任务完后，会执行这个期间产生的所有微任务
- 宏任务不单包含定时器事件，也包含同步代码

**Comment by ppatch** [comment]
`js

var a = 0;
var b = async () => {
  a = a + (await 10);
  console.log('2', a); // -> 10 
};
b();
a++;
console.log('1', a); // -> 1
`
1. async函数没到await都是同步，到await时进异步微任务队列，此时保存了上下文a为0,
2.执行a++: -> 1，最后清空微任务:-> 10

**Comment by ScarecrowG** [comment]
```b()```执行的时候，此时a为0，b保存了a的值，由于是异步任务，丢进微任务队列，执行```a++;console.log('1', a); // 1 1```宏任务执行完，执行微任务队列，```a = 0 + 10```，所以```console.log('2', a); // '2' 10```

**Comment by l0ng09** [comment]
```js
var a = 0
var b = async () => {
  a = a + await 10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？

// 1  1
// 2  10

// 执行b的时候 ，在 await 之前是同步的代码，所以 a = a + await 10 这里的a 为0， 
// await 之后是异步的会被压入到微任务队列中后面继续执行
// a++ a的值变为1
// 打印出 1 1 
// 执行栈代码清空，从微任务队列中取出来继续执行 此时打印出 2 10
```

**Comment by makejun168** [comment]
### 本题考察点
1. 宏任务 微任务 执行顺序 async await语法执行顺序 事件循环机制
2. 在 async 函数中 遇到 await 执行之前的代码块都是同步执行的

### 答案
1，1
2，10

### 拓展
1. 加入 setTimeout 等定时任务，在 await 前执行定时任务，再看看他的结果
2. 宏任务不单包含定时器事件，也包含同步代码 （之前一直不理解 为啥同步代码也会包含宏任务 这里就可以解释）
3. 
```js
var a = 0
var b = async () => {
  setTimeout(() => {
    a++;
    console.log(a);
  }, 0)
  a = a + await 10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？
```

**Comment by Turkyden** [comment]
```js
var a = 0
var b = async () => {
  a = a + await 10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？
```

输出：

```text
'1', 1
'2', 10
``

- async 是生成器的语法糖，会生成一个 promise 对象，没有遇到 await 时，是同步执行，打印 '1', 1
- a = 0 存储上下文至 b 中，在事件循环中进入微任务队列，等待主线程宏任务执行完毕，执行异步任务，打印 '2', 10

**Comment by justworkhard** [comment]
1 1
2 10，
个人觉得重点有2个：
一：await会将后续代码放入微任务中，所以会后面执行。
二：js的计算顺序，先确定左边，再确定右边

**Comment by ErnestWangZuNian** [comment]
1. js执行的时候从上往下执行 进入b的时候 a=0, 遇到await 将异步任务await 10后面的内容加入异步任务队列
2. 继续往下执行 a++ 打印a为1
3. 同步任务执行完毕 空闲了去执行异步任务 await 10 这里其实我疑惑了一下 此时的a应该是1 打印出来是11才对 但是异步任务保存的应该是触发的时候的值0 所以打印的是10

**Comment by learnRy** [comment]
```Javascript
var a = 0
var b = async () => {
  a = a + await 10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？
// 1, 1
// 2, 10
//原因 b() 执行的时候，会执行到await 之前的10，await是generator的语法糖， 会保留调用栈的数据，这个时候a的值为0
//继续执行同步代码先打印 1,1，接着继续执行异步打印 2， 2
```

**Comment by learnRy** [comment]
```Javascript
var a = 0
var b = async () => {
  a = a + await 10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？
// 1, 1
// 2, 10
//原因 b() 执行的时候，会执行到await 之前的10，await是generator的语法糖， 会保留调用栈的数据，这个时候a的值为0
//继续执行同步代码先打印 1,1，接着继续执行异步打印 2， 2
```

**Comment by dorothyDing** [comment]
'1' 1
'2' 10

解释：
1. async遇到await 会把async 函数里await 10后面的代码放入微队列

**Comment by hua-bang** [comment]
1，1
2，10

在题目中我们可以看到，b是一个异步函数，所以当函数执行到a = a + await 10 时候，这里会产生一个微任务，当此时语句相当于a = 0 + await 10， 所以下方的ａ++和 console.log(“1”,a)会先执行，故结果为
1 1
2 10

**Comment by Chrisyjs** [comment]
``` javascript
    var a = 0
    var b = async () => {
      a = a + await 10  // 丢进微任务队列，并且 js 加法运算执行是先确定左边的值再确定右边的值，此时保存的 a 是 0
      console.log('2', a) // 10
    }
    b()
    a++
    console.log('1', a) // 1

  // 下面这种情况就不一样了
    var a = 0
    var b = async () => {
      const t = await 10
      a = a + t
      console.log('2', a) // 11
    }
    b()
    a++
    console.log('1', a) // 1
```

**Comment by LISIJING** [comment]
答案：'1',1; '2',10
[https://www.babeljs.cn/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=DYUwLgBAhhC8EAYDcAoUkBGdoGcCeAdgMYQAUAlHAHwQDeKEj02MA1GVAO5QCWkAjAnKomEIgHsCOcaAB0wcQHNSAcgBMKgDTRhKAL6oMFVFFatUEqTJDylq_lp1IgA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=script&lineWrap=true&presets=env%2Cstage-2&prettier=true&targets=&version=7.13.14&externalPlugins=](url)
通过babel在线转换，可以看到在 regenerator的步骤里，第一步就取值a=0,并保存在context里，等到同步代码都执行完，到下次next方法执行的时候已经取的是contxt里的a了

**Comment by mengzhe510** [comment]
答案
1 1
2 10
1、先执行b，b为异步函数，在await之前为同步执行，在a=a+await 10中，js执行顺序为从左到右，先确定左边的a为0，右边为await 10，进入异步队列，等待同步任务执行完毕
2、a++后，a为1
3、打印 1 1
4、然后执行异步函数，由于a + await 10中左侧的a，在进入异步队列前，已经确认为0，所以此时打印 2 10

**Comment by chen870370470** [comment]
答案：
1 1
2 10
原因：await之前是按顺序执行，因此可以理解是a = 0 + await 10，然后执行a++，a为1，打印1 1。然后去执行 a= 0 + 10 打印2 10。

**Comment by Leexuetao** [comment]
// 1 1
// 2 10
考察知识点1、event loop
执行顺序1、a=0
       2、b()
       3、a = a+ await 10 
       // await后面的相当于 new Promise((resolve, reject) => {let 值引用 =a; resolve(10)}).then((res) =>{ a = 值引用 +res;console.log('2', a)})
       // promise微任务放进微任务栈之中
       4、a++
       5、console.log('1', a) // -> 输出1 1
       6、然后执行微任务栈中的 a = 0 + 10 
       7、console.log('2', a) // -> 2 10

**Comment by docterlei** [comment]
```
'1'    1
'2'    10

// 请说明输出内容，并解释为什么
// 执行 b 的时候 此时 a = 0  因为有await 所以函数先返回 等异步操作完成再执行后面的y语句 所以 a = a + (await 10) 可以看成 var // temp = await 10; a = a + temp
// 执行 a++ 打印 '1' 1
// 然后执行 await 后面的语句 由上可知 a = 0 + 10; 打印 '2' 10
```

**Comment by ByeLe** [comment]
会打印  1 1  2 10

> 原因:

`async修饰符作用`：async函数可能包含0个或者多个await表达式。await表达式会暂停整个async函数的执行进程并出让其控制权，只有当其等待的基于promise的异步操作被兑现或被拒绝之后才会恢复进程。promise的解决值会被当作该await表达式的返回值。使用async / await关键字就可以在异步代码中使用普通的try / catch代码块。(来自MDN)

async函数一定会返回一个promise对象。如果一个async函数的返回值看起来不是promise，那么它将会被隐式地包装在一个promise中。
```javascript
async function foo() {
   return 1
}
// 等价于
function foo() {
   return Promise.resolve(1)
}
```

`async函数的函数体可以被看作是由0个或者多个await表达式分割开来的。从第一行代码直到（并包括）第一个await表达式（如果有的话）都是同步运行的。这样的话，一个不含await表达式的async函数是会同步运行的。然而，如果函数体内有一个await表达式，async函数就一定会异步执行。`

`await修饰符的作用：`await 表达式会暂停当前 async function 的执行，等待 Promise 处理完成。若 Promise 正常处理(fulfilled)，其回调的resolve函数参数作为 await 表达式的值，继续执行 async function。

若 Promise 处理异常(rejected)，await 表达式会把 Promise 的异常原因抛出。

另外，如果 await 操作符后的表达式的值不是一个 Promise，`若 Promise 处理异常(rejected)，await 表达式会把 Promise 的异常原因抛出。

另外，如果 await 操作符后的表达式的值不是一个 Promise，则返回该值本身。因此`await 10`返回的是10 自身。

基于以上特性，我们可以将题目翻译成如下：
```javascript

var a = 0
var b = async () => {
   // 因为是加号操作相当于 a的值已经被取出来了，已经是一个确切的值了，不在是指向全局作用域的a了,根据刚才上面的性质，await会阻塞当前的async修饰的函数，将他之后的语句添加到异步任务队列里面去。
  a = a + await 10 
  //在执行完console.log('1', a)这个同步任务之后，此时已经没有其他的同步任务执行了，在执行下一个宏任务之前，会先看有没有微任务，此时正好有，执行这个
  console.log('2', a) // -> ？
}
b()
a++ // 因为上面的赋值操作还在异步任务队列，并没有执行，所以此时a 还是0
console.log('1', a) // -> ？ a = 0 + 1;
```

**Comment by 1742284240** [comment]
1 0
2 10

首先执行b()， a = a + await 10的时候，函数变成异步执行，a = 0 + await 10被丢到微任务队列;
然后执行宏任务
a++；
打印  1  0；
宏任务执行完成，去微任务队列执行微任务（清空微任务）
a = 0 + 10；
打印  2 10

**Comment by Ecaknight** [comment]
```js
var a = 0
var b = async () => {
  a = a + await 10
  console.log('2', a) // -> ？
}
b()
a++
console.log('1', a) // -> ？

1 1
2 10
第一个输出 1， 是因为a++ 执行之后 就输出 1
第二个输出10， async/await 是异步执行，b的函数中a会先拿到a的初始值0， 到执行await 10的后，a 最终打印的值是10

```

**Comment by niices** [comment]
答案：
1 1
2 10

过程：
函数从上往下执行到函数b内
执行到a=a+await 10时遇到await
退出函数b将await之后的内容放入微任务
此时a=0+await 10

接下来继续执行宏任务
a++ 此时a的值为1
console出 1 1

宏任务执行完成之后检查微任务队列
执行await之后的内容
此时a=0+10
console出 2 10

**Comment by sunsmeil** [comment]
- 输出 1 1；2 10。
- 考察的点是事件循环
- b函数被调用，可以理解await 后边的代码被promise.then 包裹放在微任务队列中。所以这个时候会继续执行主程序。先打印 1 1
- 然后在微任务队列执行，await 内部是生成器（主协程+gen协程）+promise实现的，内部变量a 并没有被++影响，拿到值10。打印 2 10.结束
