### ISSUE TITLE
第二十一题：Vue 有了数据劫持为什么还要 DOM diff？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#27]
Vue 有了数据劫持为什么还要 DOM diff？这不是多此一举么。

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by Turkyden** [comment]
Marked

**Comment by huangping-code** [comment]
> 这个应该要问vue作者，我猜是因为一个组件好像只有一个一个watcher，不diff怎么知道具体变化呢？没读过vue源码，读过源码得人应该知道吧

**Comment by sunsmeil** [comment]
vue 的响应式系统通过依赖收集可以直接知道在哪里变化。但是绑定需要watcher,如果粒度很细就需要很多watcher很大的开销。所以vue采用的是中等粒度，在组件级别监听。然后系统可以知道哪个组件变化，对该组件进行dom diff。

**Comment by louwenqiang** [comment]
个人感觉 数据劫持也只是知道被劫持数据发生了变化，需要去update  试图， 但是具体说要更新到哪个DOM  ，DOM结构会发生怎么样的变化，还是需要来做一个新旧的diff

**Comment by Chrisyjs** [comment]
- 现代框架主要有两种侦测数据变化方式
    - pull：React 通过 setState 显示更新，然后 VDOM 层层 Diff，查找变化
    - push：Vue 数据变化，响应式系统立刻知道哪里变化，但是一个数据就要绑定一个 Watcher。一旦绑定的颗粒度过高，就会产生大量 Watcher，增加内存消耗及依赖追踪的开销；而颗粒度过低就不能精准侦测变化。Vue 在组件级别进行响应式侦测，组件内部通过 Diff 算法查找变化。所以 Vue 是 pull + push

**Comment by makejun168** [comment]
### 数据劫持
Vue 2.0 数据劫持实现方式是 Object.defineProperty Vue 3.0+ 用的是 Proxy
具体方法初步实现如下
```js
let obj = {
    name: ''
};

obj = new Proxy(obj, {
    get(target, prop) {
        console.log('a')
        return target[prop]
    },
    set(target, prop, value) {
        console.log('b')
        target[prop] = value
    }
})

// 绑定HTML 上面的值设置好 数据更改影响视图
function observer() {
    spanName.innnerHTML = obj.name;
    inpName.value = obj.name;
}

observer();

setTimeout(() => {
    obj.name = '测试'
}, 1000);

inpName.oninput = function () {
    obj.name = this.value
}
```
### 答案
从代码可以很明显看出 这里是不涉及到到底我要更新哪个DOM的 只是知道数据更新，然后去更新数据。
所以需要 DOM diff算法 去比较

### 关于爆栈
爆栈一般是因为循环引用的问题，具体解决方法是类似于 用 new WeakSet 进行处理循环应用的问题？具体我不太清楚

**Comment by muzishuiji** [comment]
VUE的数据劫持需要绑定Watcher,通知相关的依赖项进行数据更新.而组件内状态可能会很多,数据相应的粒度做的太细会导致性能损耗过大,所以VUE在组件间采用数据劫持的方法,知道是哪个组件的数据更新,然后组件内部使用 dom diff ,更新发生了数据变化的DOM.

**Comment by BigDeep** [comment]
> VUE的数据劫持需要绑定Watcher,通知相关的依赖项进行数据更新.而组件内状态可能会很多,数据相应的粒度做的太细会导致性能损耗过大,所以VUE在组件间采用数据劫持的方法,知道是哪个组件的数据更新,然后组件内部使用 dom diff ,更新发生了数据变化的DOM.

marked
关于爆栈问题：
lodash 的deepClone遇到环形对象时，也是遇到了同样的方案。

**Comment by xt1995726** [comment]
依赖收集到通知组件update，具体更新哪些节点是需要diff做处理，至于为什么不采用细粒度更高的监听，应该就和上面的老哥说的差不多，更细化的watcher会牺牲更多的性能，性价比不高。

爆栈的问题应该说的是vue采用递归的方式对数据劫持吧，遇到大量数据的时候是需要脱离vue的数据劫持模式的，一种方法是可以采用函数的形式传递数据，如果还有其他方法希望有老哥可以告诉我

**Comment by SunshineZJJ** [comment]
通过dom diff来对比新旧dom 不同的地方以及需要做更新的地方汇总后进行具体的修改回显到画面

**Comment by niices** [comment]
1.组件的高度抽象化
2.可以更好的实现 SSR，同构渲染等
3.框架跨平台

**Comment by yiyu66** [comment]
VUE通过Object.definedProperty监听到对象属性的get和set，在数据变动时发布消息给订阅者，触发相应的监听回调。深度监听时需要递归到底，深层遍历导致性能下降。通过楼上老哥了解到proxy的优点可以直接监听数组的变化。vue在组件级进行push检测的方式(即依赖响应式系统)，在组件内部进行Virtual Dom Diff获取更加具体的差异
