### ISSUE TITLE
第二十三题：普通函数和箭头函数的区别是什么？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#29]
普通函数和箭头函数的区别是什么？

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by Turkyden** [comment]
箭头函数是 ES6 里的新特性，是描述函数的一种方式。

主要区别有：

- 上下文 this 穿透
- 生成局部作用域

**Comment by goldEli** [comment]
### 1. 写法不一样
### 2. `箭头函数` 内部不能访问 `arguments` 对象。
![image](https://user-images.githubusercontent.com/18217162/113955876-21b0b800-984f-11eb-969c-1c434627631f.png)
### 3. `箭头函数` 没有自己的 `this`， `箭头函数`的 `this` 与最近的外层普通函数 `this` 绑定。
### 4. `箭头函数` 不能作为构造函数。
![image](https://user-images.githubusercontent.com/18217162/113955968-51f85680-984f-11eb-892b-11e392c5007a.png)
### 5. `箭头函数` 参数不能重名
![image](https://user-images.githubusercontent.com/18217162/113956090-866c1280-984f-11eb-8d45-896cafad10cf.png)

**Comment by niices** [comment]
### 1.箭头函数不会创建自己的 this
箭头函数没有自己的 this ，它会捕获自己在定义时（注意，是定义时，不是调用时）所处的外层执行环境的 this ，并继承这个 this 值。所以，箭头函数中 this 的指向在它被定义的时候就已经确定了，之后永远不会改变。
### 2.箭头函数中的 this 永远不会改变
即使 .call()/.apply()/.bind() 也无法改变箭头函数中 this 的指向
### 3.箭头函数不能作为构造函数使用
### 4.箭头函数没有自己的arguments
### 5.箭头函数没有原型prototype

**Comment by mynamexiaohui** [comment]
1. 箭头函数不能作为构造函数，不能使用new
2. 箭头函数没有arguments，所以只能使用扩展运算符来代替
3. 箭头函数不会绑定this，它会捕获函数上下文中的this，并且不会改变
4. 箭头函数没有原型对象
5. 箭头函数不能被当作generate函数，也不能使用yield

**Comment by fantasticfbaby** [comment]
1. 箭头函数没有自己的this，它的this是箭头函数在定义时所处的外部环境的this
2. 箭头函数的this无法改变
3. 箭头函数的没有arguments
4. 箭头函数无法作为构造函数，在创建时也没有对应的prototype属性

**Comment by makejun168** [comment]
#### 普通函数和箭头函数的区别是什么
1. 箭头函数 不能 new 实例化 但普通函数可以，Uncaught TypeError: 箭头函数 is not a constructor，箭头函数没有 protoType
2. 箭头函数内的 this 指向外层的 this，创建箭头函数时，就已经确定了它的 this 指向，而且箭头函数的 this 不能被修改 ；普通函数的 this 指向的是调用他的对象

```js
var testa = {
    a: () => {
        console.log(this);
    },
    b: function() {
        console.log(this);
    }
}
testa.a(); // window
testa.b(); // testa
```
3. 箭头函数没有arguments，caller，callee
```js
let testb = (b)=>{
  console.log(arguments);
}

let testa = function(data) {
    console.log(arguments);
}
testa(2,92,32,32);
testb(2,92,32,32);   // Uncaught ReferenceError: arguments is not defined
```
4. 箭头函数通过 apply call 调用的，不会改变this的指向，只会传入参数

```js
let obj1 = {
    a: 10,
    b: function(n) {
        function f(n) {
            return n + this.a
        }
        return f(n);
    },
    c: function(n) {
        let f = (n) => n + this.a;
        let m = {
            a: 20
        };
        return f.call(m,n);
    }
};
console.log(obj1.b(1));  // NaN
console.log(obj1.c(1)); // 11
```

**Comment by Chrisyjs** [comment]
普通函数和箭头函数的区别：
- 写法不同
- 后者内部没有 this，需要根据作用域查找，并且不能被 call 等改变
- 后者没有 arguments
- 后者不能作为构造函数
- 后者没有 prototype 显示原型属性
- 前者可以具名和匿名，后者只能是匿名函数

**Comment by SunshineZJJ** [comment]
1.写法不一样，this指向不一样，箭头继承父亲的指向，非箭头指向调用
2.箭头this不可修改，内部没有arguments和原型,所以不能以构造函数方式调用
3.箭头只能是不具名函数

**Comment by zlv2s** [comment]
- 箭头函数没有定义自己的 `arguments`, `super`, `this`, `new.target` 绑定，在箭头函数里面如果引用了这些，会去箭头函数的词法环境中查找
- 箭头函数没有 `[[Construct]]` 这个内部方法，不能当做构造函数来使用
...

**Comment by Shinedi** [comment]
1.箭头函数写法更加简洁
2.箭头函数没有this，它的this是定义时外部执行环境的this
3. 箭头函数的this不能改变，无论是在哪里调用、被谁调用都不会改变
4. 箭头函数不能作为构造函数
5. 箭头函数没有原型

**Comment by 52js** [comment]
1、箭头函数是匿名函数，不能作为构造函数，不能使用new
2、箭头函数不绑定arguments，取而代之用rest参数...解决
3、箭头函数不绑定this，会捕获其所在的上下文的this值，作为自己的this值
4、箭头函数通过call()或apply()方法调用一个函数时，只传入了一个参数，对this并没有影响
5、箭头函数没有原型属性
6、箭头函数不能当做Generator函数,不能使用yield关键字

**Comment by dorothyDing** [comment]
1. 箭头函数内部没有自己的this，内部的this是外层this，所以不能动态改变this，不能使用new命令。
2. 箭头函数内部没有arguments对象
3. 内部不能yield命令

**Comment by louwenqiang** [comment]
箭头函数不是构造函数，无法new 一个实例  所以也没有原型一说，
箭头函数无法修改this指向，即使使用，bind apply call方法，它的this是继承外部环境的this，
箭头函数没有arguments

**Comment by keien411** [comment]
写法更简单
箭头函数的this是外部上下文的this，能拿到外部的变量
普通函数的this是当前函数的this，只能访问函数内的变量

**Comment by qll19930105** [comment]
1. 箭头函数不能作为构造函数，因为没有自己的this对象
2. 箭头函数this指向外部函数
3. 箭头函数写法更简单

**Comment by liuestc** [comment]
```
obj={
    b:function(){
        console.log(this)
    },
    a:()=>{
        console.log(this)
    }
}
obj.a() //window
// 箭头函数中的this实际是继承的它定义时所处的全局执行环境中的this，所以指向Window对象，（这里要注意，定义对象的大括号{}是无法形成一个单独的执行环境的，它依旧是处于全局执行环境中！！）

obj.b() //obj

var id = 'Global';
// 箭头函数定义在全局作用域
let fun1 = () => {
    console.log(this.id)
};

fun1();     // 'Global'
// this的指向不会改变，永远指向Window对象
fun1.call({id: 'Obj'});     // 'Global'
fun1.apply({id: 'Obj'});    // 'Global'
fun1.bind({id: 'Obj'})();   // 'Global'

```


1. 箭头函数没有arguments
2. 箭头函数不能被new，即没有constructor，也没有原型链概念
3.  >箭头函数不会创建自己的this，所以它没有自己的this，它只会从自己的作用域链的上一层继承this。 箭头函数在定义时确定了this的指向
4. bind/call/apply  不会影响this指向

**Comment by AbigaiL533** [comment]
1、箭头函数的this无法修改
2、箭头函数不能作为构造函数，不可以new一个箭头函数，也没有自己的protoType
3、箭头函数不能当做gennrator函数
4、箭头函数没有arguments

**Comment by monadaa** [comment]
1. 箭头函数不会创建自己的this，所以它没有自己的this，它只会从自己的作用域链的上一层继承this。箭头函数没有自己的this，它会捕获自己在定义时（注意，是定义时，不是调用时）所处的外层执行环境的this，并继承这个this值。所以，箭头函数中this的指向在它被定义的时候就已经确定了，之后永远不会改变。
2. 普通函数作为对象的方法调用时，this指向它所属的对象。
// 这里要注意，定义对象的大括号{}是无法形成一个单独的执行环境的，它依旧是处于全局执行环境中！！
3. 箭头函数继承而来的this指向永远不变（重要！！深入理解！！）
4. .call()/.apply()/.bind()无法改变箭头函数中this的指向
5. 箭头函数不能作为构造函数使用
6. 箭头函数没有自己的arguments
7. 箭头函数没有原型prototype
8.箭头函数不能用作Generator函数，不能使用yeild关键字

**Comment by huahua5525** [comment]
1、箭头函数是匿名函数，不能作为构造函数，不能使用new
2、箭头函数没有this
3、箭头函数没有arguments

**Comment by chen870370470** [comment]
1.箭头函数体内的this对象，就是定义时所在的对象，而不是使用时所在的对象。
2.箭头函数不可以当作构造函数，也就是说，不可以使用new命令，否则会抛出一个错误。
3.箭头函数不可以使用arguments对象，该对象在函数体内不存在。如果要用，可以用Rest参数代替。
4.箭头函数不可以使用yield命令，因此箭头函数不能用作Generator函数。

**Comment by ByeLe** [comment]
1.箭头函数不能作为构造函数
2. 箭头函数中的this,指向的是第一个不是箭头函数的父类的this
3. 箭头函数不能使用arguments对象，可以用Rest代替
4. 箭头函数不可以使用yield命令，因此箭头函数不能用作Generator函数。

**Comment by yiyu66** [comment]
箭头函数不能使用arguments、super和new.target,也不能用作构造函数。箭头函数没有prototype属性

**Comment by hua-bang** [comment]
1.首先，写法上不同
2.普通函数和箭头函数的this指向不同，普通函数中的this需要看调用者，而箭头函数的this在声明时已经定义，指向定义时的所在作用域的this。
3.箭头函数不可以作为构造函数，不可以用new
4.箭头函数只能是匿名函数
5.箭头函数不可以使用yield命令，因此箭头函数不能用作Generator函数。
6.箭头函数不能使用arguments
7.箭头函数没有prototype属性

**Comment by sunsmeil** [comment]
- 没有自己的this, arguments, super 或new.target
- 继承作用域链上一层this
- 通过call apply调用会忽略第一个参数
- 与new 一起使用会报错
- 没有prototype属性
- yield 关键字不能在箭头函数中使用。不能作函数生成器

**Comment by yanxiaolazy** [comment]
- 写法上不同
- 没有自己的this，内部使用this通过词法作用域查找。普通函数的this需要视情况而定
- 不能通过new关键字实例化对象
- 没有arguments对象，可以使用解构操作保存所有参数
- 没有prototype属性
- 不能使用yield关键字，因此无法作为生成器

**Comment by Leexuetao** [comment]
1、普通函数的this可以改变，箭头函数的this固定，就是定义时所在的对象，而不是使用时所在的对象。
2、箭头函数不可以当作构造函数，也就是说，不可以使用new命令，否则会抛出一个错误。
3、箭头函数不可以使用arguments对象，该对象在函数体内不存在。如果要用，可以用 rest 参数代替。
4、箭头函数不可以使用yield命令，因此不能用作 Generator 函数。

**Comment by Leexuetao** [comment]
1、写法不同，箭头函数更简洁
2、普通函数的this可以改变，箭头函数的this固定，就是定义时所在的对象，而不是使用时所在的对象。
3、箭头函数不可以当作构造函数，也就是说，不可以使用new命令，否则会抛出一个错误。
4、箭头函数不可以使用arguments对象，该对象在函数体内不存在。如果要用，可以用 rest 参数代替。
5、箭头函数不可以使用yield命令，因此不能用作 Generator 函数。

**Comment by zhangyingcai** [comment]
箭头函数、没有prototype、没有自己的this指向、不可以使用arguments、自然不可以new。

**Comment by wangyuanyuan0521** [comment]
ES6中定义的时候绑定this的具体含义，应该继承的是父执行上下文里面的this，切忌是父执行上下文！！！（箭头函数则是根据该函数在“谁”的作用域里，则this就是“谁”）

**Comment by dogloving** [comment]
![image](https://user-images.githubusercontent.com/17293065/117424500-6b76e600-af54-11eb-9507-61bc9cc2889b.png)
