### ISSUE TITLE
第二十五题：三问闭包

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#31]
- 闭包是什么？
- 闭包解决了什么问题？
- 为什么它还能访问到本该被销毁的变量？

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by keien411** [comment]
1. 函数B能引用到函数A的变量，函数B就是闭包
2. 闭包缓存了上级作用域，比如Ajax成功回调，回调了整个上级作用域的访问和操作能力，更加的方便
3. 闭包是建立在一个函数内部的子函数，由于能访问上级函数作用域的关系，即使上级函数执行完，作用域中的变量依旧存活在内存中，无法被释放。

**Comment by makejun168** [comment]
mark

**Comment by Chrisyjs** [comment]
- 闭包是：根据词法作用域，内部函数可以访问到外部函数中声明的变量，这些变量的集合就是闭包
  - 由于闭包可以缓存上级作用域，那么就使得函数外部打破了“函数作用域”的束缚，可以访问函数内部的变量。例如 ajax、事件绑定、setTimeout 等回调等都属于闭包
  - 因为虽然外部函数执行完毕，执行上下文销毁（栈中销毁了），但是内部函数引用外部函数的变量依旧存在堆内存中，没有销毁

**Comment by zhangyingcai** [comment]
闭包：
函数a返回函数b,函数b引用了函数a的变量，函数b就是闭包。
闭包是为了解决变量私有化。防止变量污染。
代码执行的时候检测到当前函数引用了上级作用域的变量（变量或者函数）不会释放被引用的变量，还可以访问到。

**Comment by Shinedi** [comment]
1. 函数A内部有一个函数B,函数B可以访问函数A的变量，函数B就是一个闭包
2. 闭包缓存了上级作用域，可以间接访问到函数内部的变量；防止变量污染
3. 代码执行的时候，访问了上级作用域的变量，即使上级函数执行完，作用域中的变量依旧存活在内存中，无法被释放。

**Comment by liyan19971108** [comment]
闭包是什么？
在闭包里面,内部的函数可以访问到外部函数作用域内的变量,但是外部的函数不能访问内部函数作用域内的变量；通俗来讲就是函数B可以访问函数A作用域中的变量，那么函数B就是闭包

闭包解决了什么问题？
 1.可以读取函数内部的变量；
2.让这些变量的值始终保存在内存中。

为什么它还能访问到本该被销毁的变量？
因为闭包实际上是建立在一个函数内部的子函数，由于其可访问上级作用域的原因，即使上级函数执行完，作用域也不会随之销毁，闭包拥有了访问上级作用域中的变量的权限，即使上级函数执行完后，作用域内的值也不会被销毁

**Comment by yiyu66** [comment]
闭包是指有权访问另一个函数作用域中变量的函数；
函数内再嵌套函数，返回到外部形成闭包；
内部函数可以引用外层的参数和变量
参数和变量不会被垃圾回收机制回收

**Comment by Turkyden** [comment]
Q: 闭包是什么？
A: 闭包是指有权访问空一个函数作用于中变量的函数

Q: 闭包解决了什么问题？
A: 可以间接访问函数内部的内部的变量，减少全局变量的污染

Q: 为什么它还能访问到本该被销毁的变量？
A: 函数执行完毕，执行下上下文被销毁，但是函数内部的变量依然存在堆内存里

**Comment by goldEli** [comment]
### 闭包是什么？
一个函数使用了外部变量就形成了闭包。
### 闭包解决了什么问题？
解决 `JavaScript` 中没有私有变量的问题
### 为什么它还能访问到本该被销毁的变量？
虽然函数执行后，执行上下文销毁了，但是作用域链并没有被销毁，所以可以通过作用域访链问到外部变量。

**Comment by niices** [comment]
### 闭包是什么？
根据MDN上的解释：一个函数和对其周围状态（lexical environment，词法环境）的引用捆绑在一起（或者说函数被引用包围），这样的组合就是闭包（closure）。

翻译成人话：一个内层函数及其引用的所有外部变量一同构成了一个闭包
### 闭包解决了什么问题？
闭包让你可以在一个内层函数中访问到其外层函数的作用域。
### 为什么它还能访问到本该被销毁的变量？
虽然外层函数执行完成之后对应的执行上下文被销毁，但是内层函数的作用域链并没有被销毁，所以我们此时仍然可以通过作用域链访问到闭包形成时的所有外部变量。

**Comment by louwenqiang** [comment]
内部函数引用外部函数作用域中的变量，外部函数执行会return 出内部函数，这个时候就形成了闭包
产生类似私有变量的效果，不会被污染
因为变量还被引用，不会进行垃圾回收

**Comment by liuestc** [comment]
关于闭包

###  what?

MDN:
> 一个函数和其对周围状态（lexical envioroment,词法环境）的引用捆绑在一起（或者说函数被引用包围），这样的组合就是闭包（closure）。也就是说，闭包让内层函数能访问外层函数的作用域。在JS中，每创建一个函数，就形成了一个闭包。

通俗解释and keyWords：

闭包=函数+词法环境的引用  
or
闭包=携带了执行环境的函数


### how?
如何用及解决了什么问题

1. 模拟私有方法()

```
var Counter = (function() {
  var privateCounter = 0;
  function changeBy(val) {
    privateCounter += val;
  }
  return {
    increment: function() {
      changeBy(1);
    },
    decrement: function() {
      changeBy(-1);
    },
    value: function() {
      return privateCounter;
    }
  }
})();

console.log(Counter.value()); /* logs 0 */
Counter.increment();
Counter.increment();
console.log(Counter.value()); /* logs 2 */
Counter.decrement();
console.log(Counter.value()); /* logs 1 */
```

why?

执行上下文包括：
1. 变量对象（variable object）
2. 作用域链（scope chain）
3. this

创建函数时，会将当前作用域引用加进自己的[[scope]]属性中，这个引用一直存在，不会因为外层函数的销毁而被回收。

**Comment by 1742284240** [comment]
- **闭包是什么？**

```js
能访问自由变量的函数，理论上JavaScript所有函数都是闭包
```

> 自由变量是指在函数中使用的，但既不是函数参数也不是函数的局部变量的变量



- **闭包解决了什么问题？**

```js
闭包可以解决全局变量污染的问题，函数变量私有化，常见的应用场景：防抖、节流。
```


- **为什么它还能访问到本该被销毁的变量？**

```js
闭包函数的 [[scope]] 中保存了 父级函数的作用域，由于js是词法作用域，所以即使父函数的执行上下文被销毁了，
闭包函数里的  [[scope]] 还保存着自由变量，自然也就能访问到自由变量了。
```

**Comment by ByeLe** [comment]
闭包是什么？
闭包是指能够访问自由变量的函数，所谓的自由变量就是既不是我的参数，又不是我函数创建的。

闭包解决了什么问题？
闭包是一种保护私有变量的机制，在函数执行时形成私有的作用域，保护里面的私有变量不受外界干扰

为什么它还能访问到本该被销毁的变量？
函数在创建的时候，会有一个[[scope]]属性，这个属性会将父变量对象保存起来。当父级函数出栈的时候，首先，存储在栈上的变量对象的地址引用会被清掉，但是这个变量对象他还被它的子函数所引用，因此垃圾回收算法并不会回收。

**Comment by sunsmeil** [comment]
- 闭包是什么
   -  在 JavaScript 中，根据词法作用域的规则，内部函数总是可以访问其外部函数中声明的变量，当通过调用一个外部函数返回一个内部函数后，即使该外部函数已经执行结束了，但是内部函数引用外部函数的变量依然保存在内存中，我们就把这些变量的集合称为闭包。比如外部函数是 foo，那么这些变量的集合就称为 foo 函数的闭包。
   - [https://static001.geekbang.org/resource/image/40/a8/40b8840480a5df4f43ad5f4e7907e3a8.png](url)

**Comment by huangping-code** [comment]
> 执行```console.dir(fun)```，可以展示出一个函数[[Scopes]]属性，即改函数的作用域链；当一个函数引用了外部函数变量时候，[[Scopes]]里面会有一个或者多个Closure对象，这个Closure对象保存着该函数和其词法环境的绑定状态
> 闭包作用：将函数与其操作的数据关联起来，还可以模拟私有变量和方法
> 第一点已经看得出来，变量被一个Closure对象引用了，不会被垃圾回收；

**Comment by dorothyDing** [comment]
1.闭包是什么？
访问了函数外部变量的函数。
2.闭包解决了什么问题？
模拟私有变量和方法，延长作用域链
3.为什么它还能访问到本该被销毁的变量？

**Comment by mengzhe510** [comment]
闭包：函数中的函数，通过返回的内部函数访问外部函数变量的函数；
解决的问题：可以访问函数中的变量，使变量在内存中长时间保留，避免全局变量的污染，加强封装性，实现了对变量的隐藏和封装；
为什么它还能访问到本该被销毁的变量：
由于内部函数可以访问外部函数的作用域，当外部函数执行完毕后，外部函数作用域依旧被内部函数引用，不会被垃圾回收机制回收，可以访问外部函数中的变量

**Comment by liangmingyu1100** [comment]
### 闭包是什么？
闭包：闭包就是能够读取其他函数内部变量的函数，子函数能够在外被调用，子函数所在的父函数的作用域不会被释放。
### 闭包解决了什么问题？
闭包解决了全局变量污染的问题，通过函数内部返回一个函数从而创造出一个函数作用域，这是ES6之前在没有块级作用域下所产生的方法。
### 为什么它还能访问到本该被销毁的变量？
这是因为在闭包中，父函数的变量在子函数中被引用，垃圾回收机制无法将其标志为可回收的变量。

**Comment by SunshineZJJ** [comment]
闭包是什么：
  闭包是函数内外沟通的桥梁，使得在函数外部可以访问到函数内部的变量。
闭包解决的问题：
避免全局变量或者局部变量的赋值污染；函数外可以访问到内部变量。
为什么可以访问到销毁变量：
Js的销毁机制在函数执行完毕会去销毁无用函数，由于闭包函数在外部被引用js默认它是有用的，不执行销毁，所以闭包中的变量一直存在内存中。（用闭包太多由于它的不销毁机制会造成内存泄漏）

**Comment by yuzeyang97** [comment]
闭包是什么：
一句话来讲:内部函数引用内部变量 并被外部所引用从而形成闭包
主要解决了什么问题：
主要是解决变量私有化 避免被污染的作用
为什么可以访问到销毁变量：
因为 js 的垃圾回收机制存在引用计数的规则，当这个值的引用次数变成 0 时，这个值才会被垃圾回收，释放内存，引用次数不为 0 ，就继续保存在内存中，所以不会被垃圾回收。

**Comment by linger0239** [comment]
1.闭包：当函数可以记住并访问所在的词法作用域时，就产生了闭包，即使函数是在当前词法作用 域之外执行。
2.解决什么问题：无论在什么地方执行，都可以继续访问定义时的词法作用域。
3.为什么它还能访问到本该被销毁的变量？ 因为闭包会持有对原始定义作用域的引用，所以该作用域不会被销毁
