### ISSUE TITLE
第二十八题：以下代码输出什么？为什么？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#34]
```js
{
 function a() {
  console.log(10);
 }
 a = 10;
 a = 210;

 function a() {
  console.log(20);
 }
 a = 30;
}

console.log(a);
```

上述代码输出什么？为什么会这样？

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by SunshineZJJ** [comment]
210，块级作用域js的bug

**Comment by Turkyden** [comment]
又是这种想奇奇怪怪的八股文，玄学~

**Comment by yuguangmao000** [comment]
我以为是30，但是结果是210，什么原因

**Comment by adam-zhou** [comment]
210  是块级作用域的原因吧，但是具体不清楚，把最外层括号去掉就是30

**Comment by liuestc** [comment]
yue，竟然不是30

**Comment by rookielzy** [comment]
输出 210

原因不太能理解，参考这篇文章：https://mp.weixin.qq.com/s/0CI53KqjzkEfPp7FvC-GcQ

**Comment by makejun168** [comment]
### 考点
1. 函数声明的变量提升
2. 大括号 ｛｝内 代码的运行逻辑

### 使用Babel 编译后，用的是 Script 模式
1. 明显可以看到函数声明时候 变量提升
2. 没搞明白为啥是输出 210，可能是浏览器引擎编译逻辑 和我这边Babel编辑逻辑不一致
```js
{
  var a = function a() {
    console.log(10);
  };

  var a = function a() {
    console.log(20);
  };

  a = 10;
  a = 210;
  a = 30;
}
console.log(a);
```

**Comment by huangping-code** [comment]
> #### 在严格模式下报错，因为```ES6```规定在块级作用域中声明函数就相当于使用let来声明变量一样，不可重复定义
> #### 在非严格模式下输出210，因为浏览器为了兼容问题，有自己的一些行为使得**两个具有相同名称a的不同绑定**
> 按我个人理解代码转义如下：([参考](https://stackoverflow.com/questions/31419897/what-are-the-precise-semantics-of-block-level-functions-in-es6))
```javascript
// 转义如下：假设 a0 为全局的a
var a0 = undefined
{
    var a = function a(){
        console.log(10);
    }
    a0 = a
    a = 10;
    a = 210;

    var a = function a() {
        console.log(20);
    }
    a0 = a
    a = 30;
}
console.log(a0);
```

**Comment by lucas270** [comment]
210，搞不懂

**Comment by ByeLe** [comment]
210  求高人指点。这是劝退吗？我跟大部分直觉一样，第一眼都是30

**Comment by Chrisyjs** [comment]
210，搞不懂+1

**Comment by dorothyDing** [comment]
210 太难了

**Comment by leeguooooo** [comment]
1. ie 10和低于10 结果是 30
2. 其他环境是210

原因： 
这个东西不太好解释， 210的原因可以理解为，全局作用域的a,拿到的值是最后一个funciton a(){}的前一个赋值

**Comment by zhangyingcai** [comment]
{
 function a() {
  console.log(10);
 }
 a = 10;
 a = 210;
 a = 30;
}

console.log(a);
打印第一个函数，好神奇！

**Comment by 523753042** [comment]
210，猜和变量提升有关。虽然不知道原因，但是觉得这题目太八股了，想不通实际意义

**Comment by 1742284240** [comment]
![image](https://user-images.githubusercontent.com/24542533/115033355-ebcd9c80-9efc-11eb-94d9-bb194e530104.png)

参考文章[一文读懂块语句中的函数声明](https://mp.weixin.qq.com/s/0CI53KqjzkEfPp7FvC-GcQ)
