### ISSUE TITLE
第二十九题：以下代码输出什么？

### ISSUE THREAD

**Issue by KieSun** [KieSun/fucking-frontend#35]
```js
const ee = eval
function test() {
  const a = 1
  const b = 2
  return function() {
    const c = 3
    ee('console.log(a, b, c)')
  }
}
test()()
```

上述代码输出什么？为什么会这样？

[去答题](#issue-comment-box)

新建了一个大厂真题每日打卡群，有意愿学习打卡的再进，**请备注打卡**。

<img src='https://yck-1254263422.cos.ap-shanghai.myqcloud.com/2021/03/21/16163277585930.jpeg' width='200px' />

**Comment by pumpkin123** [comment]
node 跑了一下，是`a is not defined`
不太明白为啥

**Comment by huangping-code** [comment]
> 报错```Uncaught ReferenceError: a is not defined```
因为如果你间接的使用 eval()，比如通过一个引用来调用它，而不是直接的调用 eval。 从 ECMAScript 5 起，它工作在全局作用域下，而不是局部作用域中，`[MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/eval)`

**Comment by huangping-code** [comment]
> 报错```Uncaught ReferenceError: a is not defined```

因为如果你间接的使用 eval()，比如通过一个引用来调用它，而不是直接的调用 eval。 从 ECMAScript 5 起，它工作在全局作用域下，而不是局部作用域中，[MDN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/eval)

**Comment by chaifuling** [comment]
报错Uncaught ReferenceError: a is not defined
![image](https://user-images.githubusercontent.com/41732517/117232151-3040be00-ae53-11eb-92ee-a4cb1f337f1d.png)
mdn 上eval 上说明 
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/eval

**Comment by Turkyden** [comment]
Marked

**Comment by Chrisyjs** [comment]
- 结果：Uncaught ReferenceError: a is not defined
- 原因：间接使用 eval，例如通过引用来调用，它工作在全局作用域下，所以访问的是全局作用域下的变量（ https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/eval ）

**Comment by dorothyDing** [comment]
会报错：Uncaught ReferenceError: a is not defined
通过引用调用eval，执行上下文是全局作用域。

**Comment by SunshineZJJ** [comment]
报错：a is not undefined，
因为自执行匿名函数作用域是window，而函数test里面声明的a，作用域是函数test内部，作用域不同所以报错
